In [1]:
import random
import numpy as np
import pandas as pd
import seaborn as sn
from numpy import std
from numpy import mean
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.metrics import confusion_matrix, accuracy_score
%matplotlib inline

In [2]:
%cd Z:\PPMI_Data\Excel_Data\Raw_And_More
df = pd.read_csv ("beta_post_Funnorm_PPMI_EPICn524final030618.csv")
df = df.round(decimals = 4)
df.head(2)

Z:\PPMI_Data\Excel_Data\Raw_And_More

,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,200973410167_R05C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
cg14817997,0.8340,0.8492,0.7730,0.8853,0.7725,0.7564,0.7198,0.7759,0.7689,0.7594,...,0.7882,0.8389,0.8453,0.7704,0.8529,0.7838,0.8069,0.8757,0.6613,0.7379
cg26928153,0.9456,0.9485,0.9622,0.9440,0.9263,0.9561,0.9130,0.9560,0.9571,0.8976,...,0.9512,0.9590,0.9571,0.9547,0.9478,0.9581,0.9480,0.9424,0.9550,0.9463

In [3]:
df.index.name ='CpG'
df.reset_index(inplace=True)
df.head(2)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg14817997,0.8340,0.8492,0.7730,0.8853,0.7725,0.7564,0.7198,0.7759,0.7689,...,0.7882,0.8389,0.8453,0.7704,0.8529,0.7838,0.8069,0.8757,0.6613,0.7379
1,cg26928153,0.9456,0.9485,0.9622,0.9440,0.9263,0.9561,0.9130,0.9560,0.9571,...,0.9512,0.9590,0.9571,0.9547,0.9478,0.9581,0.9480,0.9424,0.9550,0.9463

In [4]:
dframe = pd.read_csv ('CpG_List_HavingCorres_GeneChr.csv')
dframe.head(2)

          CpG
0  cg18478105
1  cg09835024

In [5]:
dfMerge = pd.merge (df, dframe, on= "CpG", how= "inner")
dfMerge.head(2)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg14817997,0.8340,0.8492,0.7730,0.8853,0.7725,0.7564,0.7198,0.7759,0.7689,...,0.7882,0.8389,0.8453,0.7704,0.8529,0.7838,0.8069,0.8757,0.6613,0.7379
1,cg26928153,0.9456,0.9485,0.9622,0.9440,0.9263,0.9561,0.9130,0.9560,0.9571,...,0.9512,0.9590,0.9571,0.9547,0.9478,0.9581,0.9480,0.9424,0.9550,0.9463

In [6]:
dft = dfMerge.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,837952,837953,837954,837955,837956,837957,837958,837959,837960,837961
CpG,cg14817997,cg26928153,cg16269199,cg13869341,cg14008030,cg12045430,cg20826792,cg20253340,cg02404219,cg21870274,...,cg08715207,cg25640065,cg02995750,cg14467015,cg15516537,cg15462332,cg00335297,cg02600718,cg10488260,cg16855331
200973410159_R03C01,0.834,0.9456,0.8452,0.9285,0.5825,0.1169,0.06,0.5232,0.7589,0.8879,...,0.2452,0.448,0.6935,0.128,0.4781,0.2701,0.2172,0.2449,0.2732,0.5393

In [7]:
dft.rename(columns=dft.iloc[0], inplace = True)

In [8]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg14817997,cg26928153,cg16269199,cg13869341,cg14008030,cg12045430,cg20826792,cg20253340,cg02404219,...,cg08715207,cg25640065,cg02995750,cg14467015,cg15516537,cg15462332,cg00335297,cg02600718,cg10488260,cg16855331
0,CpG,cg14817997,cg26928153,cg16269199,cg13869341,cg14008030,cg12045430,cg20826792,cg20253340,cg02404219,...,cg08715207,cg25640065,cg02995750,cg14467015,cg15516537,cg15462332,cg00335297,cg02600718,cg10488260,cg16855331
1,200973410159_R03C01,0.834,0.9456,0.8452,0.9285,0.5825,0.1169,0.06,0.5232,0.7589,...,0.2452,0.448,0.6935,0.128,0.4781,0.2701,0.2172,0.2449,0.2732,0.5393

In [9]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg14817997,cg26928153,cg16269199,cg13869341,cg14008030,cg12045430,cg20826792,cg20253340,cg02404219,...,cg08715207,cg25640065,cg02995750,cg14467015,cg15516537,cg15462332,cg00335297,cg02600718,cg10488260,cg16855331
1,200973410159_R03C01,0.834,0.9456,0.8452,0.9285,0.5825,0.1169,0.06,0.5232,0.7589,...,0.2452,0.448,0.6935,0.128,0.4781,0.2701,0.2172,0.2449,0.2732,0.5393
2,200991620021_R01C01,0.8492,0.9485,0.9115,0.8854,0.537,0.097,0.0834,0.5393,0.6704,...,0.0342,0.8731,0.8876,0.8508,0.86,0.8706,0.7423,0.2477,0.8458,0.5197

In [10]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg14817997,cg26928153,cg16269199,cg13869341,cg14008030,cg12045430,cg20826792,cg20253340,cg02404219,...,cg08715207,cg25640065,cg02995750,cg14467015,cg15516537,cg15462332,cg00335297,cg02600718,cg10488260,cg16855331
1,200973410159_R03C01,0.834,0.9456,0.8452,0.9285,0.5825,0.1169,0.06,0.5232,0.7589,...,0.2452,0.448,0.6935,0.128,0.4781,0.2701,0.2172,0.2449,0.2732,0.5393
2,200991620021_R01C01,0.8492,0.9485,0.9115,0.8854,0.537,0.097,0.0834,0.5393,0.6704,...,0.0342,0.8731,0.8876,0.8508,0.86,0.8706,0.7423,0.2477,0.8458,0.5197

In [11]:
df2 = pd.read_csv ("Comm10FeatData_withBasicDetails.csv")
df2.head(2)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,MDS_Depress,MDSP_Constipate,MDSP_Fatigue,MDSP_LightHead,MDSP_SleepDay,MDSP_Pain,Montreal_Cognitive,SCOPA_Sex,Symbol_Digit,UPSIT_3
0,200973410159_R03C01,3000,2,2,0,69.1,4,1,0,0,0,1,0,0,0,0,0
1,200991620021_R01C01,3001,1,1,2,65.1,4,0,0,1,0,1,0,0,2,1,1

In [12]:
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
df3.head(2)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,MDS_Depress,MDSP_Constipate,MDSP_Fatigue,...,cg08715207,cg25640065,cg02995750,cg14467015,cg15516537,cg15462332,cg00335297,cg02600718,cg10488260,cg16855331
0,200973410159_R03C01,3000,2,2,0,69.1,4,1,0,0,...,0.2452,0.448,0.6935,0.128,0.4781,0.2701,0.2172,0.2449,0.2732,0.5393
1,200991620021_R01C01,3001,1,1,2,65.1,4,0,0,1,...,0.0342,0.8731,0.8876,0.8508,0.86,0.8706,0.7423,0.2477,0.8458,0.5197

In [13]:
df_data = df3.drop(['Sentrix', 'PATNO', 'Gender', 'Age', 'AgeCate', 'HYS', 'SCOPA_Sex',
                  'MDS_Depress', 'MDSP_Constipate', 'MDSP_Fatigue','MDSP_LightHead',
       'MDSP_SleepDay', 'MDSP_Pain', 'Montreal_Cognitive', 'Symbol_Digit',
       'UPSIT_3'], axis=1)
df_data.head(2)

,APPRDX,cg14817997,cg26928153,cg16269199,cg13869341,cg14008030,cg12045430,cg20826792,cg20253340,cg02404219,...,cg08715207,cg25640065,cg02995750,cg14467015,cg15516537,cg15462332,cg00335297,cg02600718,cg10488260,cg16855331
0,2,0.834,0.9456,0.8452,0.9285,0.5825,0.1169,0.06,0.5232,0.7589,...,0.2452,0.448,0.6935,0.128,0.4781,0.2701,0.2172,0.2449,0.2732,0.5393
1,1,0.8492,0.9485,0.9115,0.8854,0.537,0.097,0.0834,0.5393,0.6704,...,0.0342,0.8731,0.8876,0.8508,0.86,0.8706,0.7423,0.2477,0.8458,0.5197

In [14]:
df_data.shape

(457, 837963)

In [ ]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,1000) :
        print(i)
        dataset = df_data.groupby('APPRDX').apply(lambda x: x.sample(100))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=1, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1

C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py:702: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

In [ ]:
dframe1.head()

In [ ]:
dframe1.to_csv ("All_CpG_PatVsHealthy_Accuracy_1000RF.csv")