In [1]:
import pandas as pd
import numpy as np

In [2]:
%cd Z:\PPMI_Data\Excel_Data\Raw_And_More
df = pd.read_csv ("beta_post_Funnorm_PPMI_EPICn524final030618.csv")
df = df.round(decimals = 4)
df.head(2)

Z:\PPMI_Data\Excel_Data\Raw_And_More

,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,200973410167_R05C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
cg14817997,0.8340,0.8492,0.7730,0.8853,0.7725,0.7564,0.7198,0.7759,0.7689,0.7594,...,0.7882,0.8389,0.8453,0.7704,0.8529,0.7838,0.8069,0.8757,0.6613,0.7379
cg26928153,0.9456,0.9485,0.9622,0.9440,0.9263,0.9561,0.9130,0.9560,0.9571,0.8976,...,0.9512,0.9590,0.9571,0.9547,0.9478,0.9581,0.9480,0.9424,0.9550,0.9463

In [3]:
df.index.name ='CpG'
df.reset_index(inplace=True)
df.head(2)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg14817997,0.8340,0.8492,0.7730,0.8853,0.7725,0.7564,0.7198,0.7759,0.7689,...,0.7882,0.8389,0.8453,0.7704,0.8529,0.7838,0.8069,0.8757,0.6613,0.7379
1,cg26928153,0.9456,0.9485,0.9622,0.9440,0.9263,0.9561,0.9130,0.9560,0.9571,...,0.9512,0.9590,0.9571,0.9547,0.9478,0.9581,0.9480,0.9424,0.9550,0.9463

In [4]:
dframe = pd.read_csv ('CpG_Common_inTop50NMIvsBoruta_9Feats.csv')
dframe.head(2)

          CpG
0  cg00377727
1  cg12298429

In [5]:
dfMerge = pd.merge (df, dframe, on= "CpG", how= "inner")
dfMerge.head(2)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg02152968,0.2690,0.2634,0.270,0.258,0.2513,0.1459,0.2311,0.2287,0.2985,...,0.2384,0.2328,0.2471,0.2445,0.2543,0.2166,0.2451,0.2201,0.2339,0.2782
1,cg12298429,0.0455,0.0328,0.029,0.037,0.0313,0.0281,0.0427,0.0318,0.0280,...,0.0302,0.0353,0.0278,0.0290,0.0357,0.0236,0.0433,0.0429,0.0298,0.0444

In [6]:
dft = dfMerge.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,28,29,30,31,32,33,34,35,36,37
CpG,cg02152968,cg12298429,cg12298429,cg12298429,cg12298429,cg08096908,cg00260798,cg03682895,cg05789720,cg05789720,...,cg00377727,cg00377727,cg24215869,cg13332222,cg13959611,cg10595406,cg18322516,cg11852879,cg18704989,cg18473117
200973410159_R03C01,0.269,0.0455,0.0455,0.0455,0.0455,0.9378,0.9244,0.9096,0.9225,0.9225,...,0.6784,0.6784,0.3951,0.9298,0.0875,0.9349,0.9369,0.9043,0.0228,0.9672

In [7]:
dft.rename(columns=dft.iloc[0], inplace = True)

In [8]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg02152968,cg12298429,cg12298429,cg12298429,cg12298429,cg08096908,cg00260798,cg03682895,cg05789720,...,cg00377727,cg00377727,cg24215869,cg13332222,cg13959611,cg10595406,cg18322516,cg11852879,cg18704989,cg18473117
0,CpG,cg02152968,cg12298429,cg12298429,cg12298429,cg12298429,cg08096908,cg00260798,cg03682895,cg05789720,...,cg00377727,cg00377727,cg24215869,cg13332222,cg13959611,cg10595406,cg18322516,cg11852879,cg18704989,cg18473117
1,200973410159_R03C01,0.269,0.0455,0.0455,0.0455,0.0455,0.9378,0.9244,0.9096,0.9225,...,0.6784,0.6784,0.3951,0.9298,0.0875,0.9349,0.9369,0.9043,0.0228,0.9672

In [9]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg02152968,cg12298429,cg12298429,cg12298429,cg12298429,cg08096908,cg00260798,cg03682895,cg05789720,...,cg00377727,cg00377727,cg24215869,cg13332222,cg13959611,cg10595406,cg18322516,cg11852879,cg18704989,cg18473117
1,200973410159_R03C01,0.269,0.0455,0.0455,0.0455,0.0455,0.9378,0.9244,0.9096,0.9225,...,0.6784,0.6784,0.3951,0.9298,0.0875,0.9349,0.9369,0.9043,0.0228,0.9672
2,200991620021_R01C01,0.2634,0.0328,0.0328,0.0328,0.0328,0.9055,0.8857,0.9027,0.9109,...,0.9233,0.9233,0.3458,0.9022,0.0443,0.9069,0.9304,0.8955,0.0129,0.9388

In [10]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg02152968,cg12298429,cg12298429,cg12298429,cg12298429,cg08096908,cg00260798,cg03682895,cg05789720,...,cg00377727,cg00377727,cg24215869,cg13332222,cg13959611,cg10595406,cg18322516,cg11852879,cg18704989,cg18473117
1,200973410159_R03C01,0.269,0.0455,0.0455,0.0455,0.0455,0.9378,0.9244,0.9096,0.9225,...,0.6784,0.6784,0.3951,0.9298,0.0875,0.9349,0.9369,0.9043,0.0228,0.9672
2,200991620021_R01C01,0.2634,0.0328,0.0328,0.0328,0.0328,0.9055,0.8857,0.9027,0.9109,...,0.9233,0.9233,0.3458,0.9022,0.0443,0.9069,0.9304,0.8955,0.0129,0.9388

In [11]:
df2 = pd.read_csv ("Comm10FeatData_withBasicDetails.csv")
df2.head(2)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,MDS_Depress,MDSP_Constipate,MDSP_Fatigue,MDSP_LightHead,MDSP_SleepDay,MDSP_Pain,Montreal_Cognitive,SCOPA_Sex,Symbol_Digit,UPSIT_3
0,200973410159_R03C01,3000,2,2,0,69.1,4,1,0,0,0,1,0,0,0,0,0
1,200991620021_R01C01,3001,1,1,2,65.1,4,0,0,1,0,1,0,0,2,1,1

In [12]:
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
df3.head(2)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,MDS_Depress,MDSP_Constipate,MDSP_Fatigue,...,cg00377727,cg00377727,cg24215869,cg13332222,cg13959611,cg10595406,cg18322516,cg11852879,cg18704989,cg18473117
0,200973410159_R03C01,3000,2,2,0,69.1,4,1,0,0,...,0.6784,0.6784,0.3951,0.9298,0.0875,0.9349,0.9369,0.9043,0.0228,0.9672
1,200991620021_R01C01,3001,1,1,2,65.1,4,0,0,1,...,0.9233,0.9233,0.3458,0.9022,0.0443,0.9069,0.9304,0.8955,0.0129,0.9388

In [13]:
df3.shape

(457, 55)

In [14]:
df3.to_csv ("CpG_Common_inTop50NMIvsBoruta_9Feats_withComm10FeatData_withMethyl.csv", index = False)