In [1]:
import pandas as pd
import numpy as np

In [2]:
%cd Z:\PPMI_Data\Excel_Data\Raw_And_More
df = pd.read_csv ("beta_post_Funnorm_PPMI_EPICn524final030618.csv")
df = df.round(decimals = 4)
df.head(2)

Z:\PPMI_Data\Excel_Data\Raw_And_More

,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,200973410167_R05C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
cg14817997,0.8340,0.8492,0.7730,0.8853,0.7725,0.7564,0.7198,0.7759,0.7689,0.7594,...,0.7882,0.8389,0.8453,0.7704,0.8529,0.7838,0.8069,0.8757,0.6613,0.7379
cg26928153,0.9456,0.9485,0.9622,0.9440,0.9263,0.9561,0.9130,0.9560,0.9571,0.8976,...,0.9512,0.9590,0.9571,0.9547,0.9478,0.9581,0.9480,0.9424,0.9550,0.9463

In [3]:
df.index.name ='CpG'
df.reset_index(inplace=True)
df.head(2)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg14817997,0.8340,0.8492,0.7730,0.8853,0.7725,0.7564,0.7198,0.7759,0.7689,...,0.7882,0.8389,0.8453,0.7704,0.8529,0.7838,0.8069,0.8757,0.6613,0.7379
1,cg26928153,0.9456,0.9485,0.9622,0.9440,0.9263,0.9561,0.9130,0.9560,0.9571,...,0.9512,0.9590,0.9571,0.9547,0.9478,0.9581,0.9480,0.9424,0.9550,0.9463

In [4]:
dframe = pd.read_csv ('CpG_450_333_FromTop50Boruta_9Feats_MethylBased.csv')
dframe.head(2)

          CpG
0  cg21092373
1  cg00377727

In [5]:
dfMerge = pd.merge (df, dframe, on= "CpG", how= "inner")
dfMerge.head(2)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg11677857,0.0667,0.1094,0.0824,0.0889,0.0968,0.0525,0.0601,0.0950,0.1682,...,0.1027,0.0902,0.1451,0.0469,0.0978,0.1701,0.0750,0.0532,0.0712,0.0708
1,cg12809925,0.5555,0.4483,0.5307,0.6143,0.5568,0.6168,0.5987,0.6169,0.4647,...,0.5546,0.4396,0.4609,0.4470,0.5052,0.4601,0.5193,0.5251,0.5934,0.5095

In [6]:
dft = dfMerge.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,319,320,321,322,323,324,325,326,327,328
CpG,cg11677857,cg12809925,cg03476938,cg04471171,cg19555872,cg19924025,cg18357560,cg09168320,cg26672954,cg00141522,...,cg07448795,cg18704989,cg00984715,cg12969734,cg25700851,cg12342861,cg18473117,cg25135411,cg18920427,cg09233704
200973410159_R03C01,0.0667,0.5555,0.6119,0.4616,0.9153,0.0304,0.8327,0.8716,0.9334,0.0798,...,0.0145,0.0228,0.5868,0.9285,0.9147,0.9134,0.9672,0.9228,0.462,0.7249

In [7]:
dft.rename(columns=dft.iloc[0], inplace = True)

In [8]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg11677857,cg12809925,cg03476938,cg04471171,cg19555872,cg19924025,cg18357560,cg09168320,cg26672954,...,cg07448795,cg18704989,cg00984715,cg12969734,cg25700851,cg12342861,cg18473117,cg25135411,cg18920427,cg09233704
0,CpG,cg11677857,cg12809925,cg03476938,cg04471171,cg19555872,cg19924025,cg18357560,cg09168320,cg26672954,...,cg07448795,cg18704989,cg00984715,cg12969734,cg25700851,cg12342861,cg18473117,cg25135411,cg18920427,cg09233704
1,200973410159_R03C01,0.0667,0.5555,0.6119,0.4616,0.9153,0.0304,0.8327,0.8716,0.9334,...,0.0145,0.0228,0.5868,0.9285,0.9147,0.9134,0.9672,0.9228,0.462,0.7249

In [9]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg11677857,cg12809925,cg03476938,cg04471171,cg19555872,cg19924025,cg18357560,cg09168320,cg26672954,...,cg07448795,cg18704989,cg00984715,cg12969734,cg25700851,cg12342861,cg18473117,cg25135411,cg18920427,cg09233704
1,200973410159_R03C01,0.0667,0.5555,0.6119,0.4616,0.9153,0.0304,0.8327,0.8716,0.9334,...,0.0145,0.0228,0.5868,0.9285,0.9147,0.9134,0.9672,0.9228,0.462,0.7249
2,200991620021_R01C01,0.1094,0.4483,0.549,0.5212,0.8797,0.0172,0.7906,0.2976,0.9266,...,0.0187,0.0129,0.4464,0.8423,0.8668,0.9178,0.9388,0.8985,0.3566,0.6201

In [10]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg11677857,cg12809925,cg03476938,cg04471171,cg19555872,cg19924025,cg18357560,cg09168320,cg26672954,...,cg07448795,cg18704989,cg00984715,cg12969734,cg25700851,cg12342861,cg18473117,cg25135411,cg18920427,cg09233704
1,200973410159_R03C01,0.0667,0.5555,0.6119,0.4616,0.9153,0.0304,0.8327,0.8716,0.9334,...,0.0145,0.0228,0.5868,0.9285,0.9147,0.9134,0.9672,0.9228,0.462,0.7249
2,200991620021_R01C01,0.1094,0.4483,0.549,0.5212,0.8797,0.0172,0.7906,0.2976,0.9266,...,0.0187,0.0129,0.4464,0.8423,0.8668,0.9178,0.9388,0.8985,0.3566,0.6201

In [11]:
df2 = pd.read_csv ("Comm10FeatData_withBasicDetails.csv")
df2.head(2)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,MDS_Depress,MDSP_Constipate,MDSP_Fatigue,MDSP_LightHead,MDSP_SleepDay,MDSP_Pain,Montreal_Cognitive,SCOPA_Sex,Symbol_Digit,UPSIT_3
0,200973410159_R03C01,3000,2,2,0,69.1,4,1,0,0,0,1,0,0,0,0,0
1,200991620021_R01C01,3001,1,1,2,65.1,4,0,0,1,0,1,0,0,2,1,1

In [12]:
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
df3.head(2)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,MDS_Depress,MDSP_Constipate,MDSP_Fatigue,...,cg07448795,cg18704989,cg00984715,cg12969734,cg25700851,cg12342861,cg18473117,cg25135411,cg18920427,cg09233704
0,200973410159_R03C01,3000,2,2,0,69.1,4,1,0,0,...,0.0145,0.0228,0.5868,0.9285,0.9147,0.9134,0.9672,0.9228,0.462,0.7249
1,200991620021_R01C01,3001,1,1,2,65.1,4,0,0,1,...,0.0187,0.0129,0.4464,0.8423,0.8668,0.9178,0.9388,0.8985,0.3566,0.6201

In [13]:
df3.shape

(457, 346)

In [14]:
df3.to_csv ("450Top50CpG_withComm10FeatData_withMethylDetail.csv", index = False)