In [1]:
import pandas as pd
import numpy as np

In [2]:
%cd Z:\PPMI_Data\Excel_Data\Raw_And_More
df = pd.read_csv ("beta_post_Funnorm_PPMI_EPICn524final030618.csv")
df = df.round(decimals = 4)
df.head(2)

Z:\PPMI_Data\Excel_Data\Raw_And_More

,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,200973410167_R05C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
cg14817997,0.8340,0.8492,0.7730,0.8853,0.7725,0.7564,0.7198,0.7759,0.7689,0.7594,...,0.7882,0.8389,0.8453,0.7704,0.8529,0.7838,0.8069,0.8757,0.6613,0.7379
cg26928153,0.9456,0.9485,0.9622,0.9440,0.9263,0.9561,0.9130,0.9560,0.9571,0.8976,...,0.9512,0.9590,0.9571,0.9547,0.9478,0.9581,0.9480,0.9424,0.9550,0.9463

In [3]:
df.index.name ='CpG'
df.reset_index(inplace=True)
df.head(2)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg14817997,0.8340,0.8492,0.7730,0.8853,0.7725,0.7564,0.7198,0.7759,0.7689,...,0.7882,0.8389,0.8453,0.7704,0.8529,0.7838,0.8069,0.8757,0.6613,0.7379
1,cg26928153,0.9456,0.9485,0.9622,0.9440,0.9263,0.9561,0.9130,0.9560,0.9571,...,0.9512,0.9590,0.9571,0.9547,0.9478,0.9581,0.9480,0.9424,0.9550,0.9463

In [4]:
%cd Z:\PPMI_Data\Excel_Data\NonMotors\Feature_CpG_Gene_Association\Xtra_Files\All_9Features
dframe = pd.read_csv ('All9_CommonCpGList.csv')
dframe.head(2)

Z:\PPMI_Data\Excel_Data\NonMotors\Feature_CpG_Gene_Association\Xtra_Files\All_9Features

          CpG
0  cg05142211
1  cg13959611

In [5]:
dfMerge = pd.merge (df, dframe, on= "CpG", how= "inner")
dfMerge.head(2)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg24183574,0.9429,0.8964,0.9326,0.9518,0.9393,0.9406,0.9239,0.9449,0.9345,...,0.9364,0.9308,0.9499,0.9308,0.9429,0.9305,0.9506,0.9333,0.9439,0.9324
1,cg00356916,0.8087,0.8478,0.8932,0.8736,0.8371,0.8469,0.8516,0.7771,0.8192,...,0.8568,0.8314,0.8517,0.8566,0.4839,0.8516,0.8751,0.8761,0.8766,0.8921

In [6]:
dft = dfMerge.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
CpG,cg24183574,cg00356916,cg12298429,cg08096908,cg00260798,cg19211931,cg03682895,cg14529754,cg05789720,cg24628866,...,cg13332222,cg13959611,cg19371224,cg12220605,cg17528967,cg03827764,cg18322516,cg11852879,cg18704989,cg18473117
200973410159_R03C01,0.9429,0.8087,0.0455,0.9378,0.9244,0.3206,0.9096,0.2781,0.9225,0.9297,...,0.9298,0.0875,0.8952,0.1173,0.869,0.9426,0.9369,0.9043,0.0228,0.9672

In [7]:
dft.rename(columns=dft.iloc[0], inplace = True)

In [8]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg24183574,cg00356916,cg12298429,cg08096908,cg00260798,cg19211931,cg03682895,cg14529754,cg05789720,...,cg13332222,cg13959611,cg19371224,cg12220605,cg17528967,cg03827764,cg18322516,cg11852879,cg18704989,cg18473117
0,CpG,cg24183574,cg00356916,cg12298429,cg08096908,cg00260798,cg19211931,cg03682895,cg14529754,cg05789720,...,cg13332222,cg13959611,cg19371224,cg12220605,cg17528967,cg03827764,cg18322516,cg11852879,cg18704989,cg18473117
1,200973410159_R03C01,0.9429,0.8087,0.0455,0.9378,0.9244,0.3206,0.9096,0.2781,0.9225,...,0.9298,0.0875,0.8952,0.1173,0.869,0.9426,0.9369,0.9043,0.0228,0.9672

In [9]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg24183574,cg00356916,cg12298429,cg08096908,cg00260798,cg19211931,cg03682895,cg14529754,cg05789720,...,cg13332222,cg13959611,cg19371224,cg12220605,cg17528967,cg03827764,cg18322516,cg11852879,cg18704989,cg18473117
1,200973410159_R03C01,0.9429,0.8087,0.0455,0.9378,0.9244,0.3206,0.9096,0.2781,0.9225,...,0.9298,0.0875,0.8952,0.1173,0.869,0.9426,0.9369,0.9043,0.0228,0.9672
2,200991620021_R01C01,0.8964,0.8478,0.0328,0.9055,0.8857,0.3231,0.9027,0.2996,0.9109,...,0.9022,0.0443,0.7516,0.0824,0.8081,0.9183,0.9304,0.8955,0.0129,0.9388

In [10]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg24183574,cg00356916,cg12298429,cg08096908,cg00260798,cg19211931,cg03682895,cg14529754,cg05789720,...,cg13332222,cg13959611,cg19371224,cg12220605,cg17528967,cg03827764,cg18322516,cg11852879,cg18704989,cg18473117
1,200973410159_R03C01,0.9429,0.8087,0.0455,0.9378,0.9244,0.3206,0.9096,0.2781,0.9225,...,0.9298,0.0875,0.8952,0.1173,0.869,0.9426,0.9369,0.9043,0.0228,0.9672
2,200991620021_R01C01,0.8964,0.8478,0.0328,0.9055,0.8857,0.3231,0.9027,0.2996,0.9109,...,0.9022,0.0443,0.7516,0.0824,0.8081,0.9183,0.9304,0.8955,0.0129,0.9388

In [11]:
%cd Z:\PPMI_Data\Excel_Data\Raw_And_More
df2 = pd.read_csv ("Comm10FeatData_withBasicDetails.csv")
df2.head(2)

Z:\PPMI_Data\Excel_Data\Raw_And_More

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,MDS_Depress,MDSP_Constipate,MDSP_Fatigue,MDSP_LightHead,MDSP_SleepDay,MDSP_Pain,Montreal_Cognitive,SCOPA_Sex,Symbol_Digit,UPSIT_3
0,200973410159_R03C01,3000,2,2,0,69.1,4,1,0,0,0,1,0,0,0,0,0
1,200991620021_R01C01,3001,1,1,2,65.1,4,0,0,1,0,1,0,0,2,1,1

In [12]:
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
df3.head(2)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,MDS_Depress,MDSP_Constipate,MDSP_Fatigue,...,cg13332222,cg13959611,cg19371224,cg12220605,cg17528967,cg03827764,cg18322516,cg11852879,cg18704989,cg18473117
0,200973410159_R03C01,3000,2,2,0,69.1,4,1,0,0,...,0.9298,0.0875,0.8952,0.1173,0.869,0.9426,0.9369,0.9043,0.0228,0.9672
1,200991620021_R01C01,3001,1,1,2,65.1,4,0,0,1,...,0.9022,0.0443,0.7516,0.0824,0.8081,0.9183,0.9304,0.8955,0.0129,0.9388

In [13]:
df3.shape

(457, 64)

In [14]:
df3.to_csv ("CpG_CommonFromAll9_withComm10FeatData_withMethyl.csv", index = False)