In [1]:
import pandas as pd
import numpy as np

In [2]:
%cd Z:\PPMI_Data\Excel_Data\Raw_And_More
df = pd.read_csv ("beta_post_Funnorm_PPMI_EPICn524final030618.csv")
df = df.round(decimals = 4)
df.head(2)

Z:\PPMI_Data\Excel_Data\Raw_And_More

,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,200973410167_R05C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
cg14817997,0.8340,0.8492,0.7730,0.8853,0.7725,0.7564,0.7198,0.7759,0.7689,0.7594,...,0.7882,0.8389,0.8453,0.7704,0.8529,0.7838,0.8069,0.8757,0.6613,0.7379
cg26928153,0.9456,0.9485,0.9622,0.9440,0.9263,0.9561,0.9130,0.9560,0.9571,0.8976,...,0.9512,0.9590,0.9571,0.9547,0.9478,0.9581,0.9480,0.9424,0.9550,0.9463

In [3]:
df.index.name ='CpG'
df.reset_index(inplace=True)
df.head(2)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg14817997,0.8340,0.8492,0.7730,0.8853,0.7725,0.7564,0.7198,0.7759,0.7689,...,0.7882,0.8389,0.8453,0.7704,0.8529,0.7838,0.8069,0.8757,0.6613,0.7379
1,cg26928153,0.9456,0.9485,0.9622,0.9440,0.9263,0.9561,0.9130,0.9560,0.9571,...,0.9512,0.9590,0.9571,0.9547,0.9478,0.9581,0.9480,0.9424,0.9550,0.9463

In [4]:
dframe = pd.read_csv ('CpG_AboveNMI.05_AllChrin_APP1vs2.csv')
dframe.head(2)

          CpG
0  cg10991923
1  cg16881640

In [5]:
dfMerge = pd.merge (df, dframe, on= "CpG", how= "inner")
dfMerge.head(2)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg00894481,0.7124,0.7681,0.8569,0.7722,0.7143,0.7208,0.6112,0.7601,0.7718,...,0.7544,0.7890,0.7231,0.8565,0.7759,0.7671,0.7455,0.7449,0.7658,0.7853
1,cg26408382,0.9030,0.9224,0.9156,0.9128,0.8930,0.9210,0.9052,0.9168,0.9256,...,0.9012,0.8989,0.9078,0.9145,0.9216,0.9108,0.9138,0.9291,0.9274,0.9154

In [6]:
dft = dfMerge.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,57
CpG,cg00894481,cg26408382,cg06796611,cg06061283,cg21672780,cg07569562,cg07617207,cg11670533,cg14707886,cg23193209,...,cg01571840,cg19726935,cg24009439,cg24374538,cg22151539,cg21890309,cg22963164,cg04685632,cg26417244,cg15469205
200973410159_R03C01,0.7124,0.903,0.7825,0.8702,0.9244,0.9243,0.9256,0.8498,0.7842,0.878,...,0.9161,0.7926,0.9665,0.1581,0.824,0.9807,0.891,0.9202,0.9081,0.6569

In [7]:
dft.rename(columns=dft.iloc[0], inplace = True)

In [8]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg00894481,cg26408382,cg06796611,cg06061283,cg21672780,cg07569562,cg07617207,cg11670533,cg14707886,...,cg01571840,cg19726935,cg24009439,cg24374538,cg22151539,cg21890309,cg22963164,cg04685632,cg26417244,cg15469205
0,CpG,cg00894481,cg26408382,cg06796611,cg06061283,cg21672780,cg07569562,cg07617207,cg11670533,cg14707886,...,cg01571840,cg19726935,cg24009439,cg24374538,cg22151539,cg21890309,cg22963164,cg04685632,cg26417244,cg15469205
1,200973410159_R03C01,0.7124,0.903,0.7825,0.8702,0.9244,0.9243,0.9256,0.8498,0.7842,...,0.9161,0.7926,0.9665,0.1581,0.824,0.9807,0.891,0.9202,0.9081,0.6569

In [9]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg00894481,cg26408382,cg06796611,cg06061283,cg21672780,cg07569562,cg07617207,cg11670533,cg14707886,...,cg01571840,cg19726935,cg24009439,cg24374538,cg22151539,cg21890309,cg22963164,cg04685632,cg26417244,cg15469205
1,200973410159_R03C01,0.7124,0.903,0.7825,0.8702,0.9244,0.9243,0.9256,0.8498,0.7842,...,0.9161,0.7926,0.9665,0.1581,0.824,0.9807,0.891,0.9202,0.9081,0.6569
2,200991620021_R01C01,0.7681,0.9224,0.729,0.732,0.9126,0.8898,0.8767,0.7905,0.8465,...,0.9195,0.6946,0.9657,0.0977,0.7136,0.9733,0.7354,0.8675,0.8952,0.8659

In [10]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg00894481,cg26408382,cg06796611,cg06061283,cg21672780,cg07569562,cg07617207,cg11670533,cg14707886,...,cg01571840,cg19726935,cg24009439,cg24374538,cg22151539,cg21890309,cg22963164,cg04685632,cg26417244,cg15469205
1,200973410159_R03C01,0.7124,0.903,0.7825,0.8702,0.9244,0.9243,0.9256,0.8498,0.7842,...,0.9161,0.7926,0.9665,0.1581,0.824,0.9807,0.891,0.9202,0.9081,0.6569
2,200991620021_R01C01,0.7681,0.9224,0.729,0.732,0.9126,0.8898,0.8767,0.7905,0.8465,...,0.9195,0.6946,0.9657,0.0977,0.7136,0.9733,0.7354,0.8675,0.8952,0.8659

In [11]:
df2 = pd.read_csv ("Comm10FeatData_withBasicDetails.csv")
df2.head(2)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,MDS_Depress,MDSP_Constipate,MDSP_Fatigue,MDSP_LightHead,MDSP_SleepDay,MDSP_Pain,Montreal_Cognitive,SCOPA_Sex,Symbol_Digit,UPSIT_3
0,200973410159_R03C01,3000,2,2,0,69.1,4,1,0,0,0,1,0,0,0,0,0
1,200991620021_R01C01,3001,1,1,2,65.1,4,0,0,1,0,1,0,0,2,1,1

In [12]:
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
df3.head(2)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,MDS_Depress,MDSP_Constipate,MDSP_Fatigue,...,cg01571840,cg19726935,cg24009439,cg24374538,cg22151539,cg21890309,cg22963164,cg04685632,cg26417244,cg15469205
0,200973410159_R03C01,3000,2,2,0,69.1,4,1,0,0,...,0.9161,0.7926,0.9665,0.1581,0.824,0.9807,0.891,0.9202,0.9081,0.6569
1,200991620021_R01C01,3001,1,1,2,65.1,4,0,0,1,...,0.9195,0.6946,0.9657,0.0977,0.7136,0.9733,0.7354,0.8675,0.8952,0.8659

In [13]:
df3.shape

(457, 75)

In [14]:
df3.to_csv ("CpG_AboveNMI.05inAllChr_withComm10FeatData_withMethylDetail.csv", index = False)