# Random Forest Classification

In [1]:
import random
import numpy as np
import pandas as pd
import seaborn as sn
from numpy import std
from numpy import mean
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.metrics import confusion_matrix, accuracy_score
%matplotlib inline

In [2]:
%cd S:\PPMI_RNA\Processed
df = pd.read_csv('All_Counts_PatAndHealthy_Disease.csv')
print(df.shape)
df.head(2)

S:\PPMI_RNA\Processed
(2110, 58782)

,HudAlphaID,DIAGNOSIS,ENSG00000223972.5,ENSG00000227232.5,ENSG00000278267.1,ENSG00000243485.5,ENSG00000284332.1,ENSG00000237613.2,ENSG00000268020.3,ENSG00000240361.2,...,ENSG00000273739.1,ENSG00000276700.1,ENSG00000276312.1,ENSG00000275757.1,ENSG00000278573.1,ENSG00000276017.1,ENSG00000278817.1,ENSG00000277196.4,ENSG00000278625.1,ENSG00000277374.1
0,5104_SL_0001,PD,15,232,15,0,0,0,0,0,...,0,1,16,1,0,2,19,0,0,0
1,5104_SL_0002,Control,2,199,10,0,0,0,0,1,...,0,0,2,0,0,0,3,0,0,0

In [3]:
df1 = df.drop(['HudAlphaID'], axis=1)
df1.head(2)

,DIAGNOSIS,ENSG00000223972.5,ENSG00000227232.5,ENSG00000278267.1,ENSG00000243485.5,ENSG00000284332.1,ENSG00000237613.2,ENSG00000268020.3,ENSG00000240361.2,ENSG00000186092.6,...,ENSG00000273739.1,ENSG00000276700.1,ENSG00000276312.1,ENSG00000275757.1,ENSG00000278573.1,ENSG00000276017.1,ENSG00000278817.1,ENSG00000277196.4,ENSG00000278625.1,ENSG00000277374.1
0,PD,15,232,15,0,0,0,0,0,0,...,0,1,16,1,0,2,19,0,0,0
1,Control,2,199,10,0,0,0,0,1,0,...,0,0,2,0,0,0,3,0,0,0

## Top 50 NMI

In [4]:
df2 = pd.read_csv('NMI_AllCounts.csv')
df2_sub = df2['Geneid'].iloc[:51]
df2_sub.head(2)

0            DIAGNOSIS
1    ENSG00000257878.1
Name: Geneid, dtype: object

In [5]:
df_50 = df1[df2_sub]
print(df_50.shape)
df_50.head(2)

(2110, 51)

,DIAGNOSIS,ENSG00000257878.1,ENSG00000268240.1,ENSG00000111490.13,ENSG00000225873.4,ENSG00000057757.9,ENSG00000152463.14,ENSG00000152484.13,ENSG00000165434.7,ENSG00000173598.13,...,ENSG00000135045.6,ENSG00000135218.18,ENSG00000257715.1,ENSG00000236320.3,ENSG00000149798.4,ENSG00000244607.6,ENSG00000166171.12,ENSG00000130433.7,ENSG00000277763.1,ENSG00000197165.10
0,PD,566,117,228,238,12244,4,6992,1052,7607,...,570,11403,17,578,58,53,518,42,134,39
1,Control,790,95,258,293,7505,9,5983,1402,4772,...,453,13652,54,387,86,39,186,20,108,64

In [6]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df2 = df_50.groupby('DIAGNOSIS').apply(lambda x: x.sample(100))
    X = df2.drop('DIAGNOSIS', axis = 1)
    y = df2['DIAGNOSIS']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.545
2
Mean accuracy: 0.65
3
Mean accuracy: 0.56
4
Mean accuracy: 0.67
5
Mean accuracy: 0.605
6
Mean accuracy: 0.6499999999999999
7
Mean accuracy: 0.63
8
Mean accuracy: 0.615
9
Mean accuracy: 0.5650000000000002
10
Mean accuracy: 0.7
11
Mean accuracy: 0.5800000000000001
12
Mean accuracy: 0.63
13
Mean accuracy: 0.62
14
Mean accuracy: 0.62
15
Mean accuracy: 0.535
16
Mean accuracy: 0.555
17
Mean accuracy: 0.6450000000000001
18
Mean accuracy: 0.685
19
Mean accuracy: 0.6
20
Mean accuracy: 0.6050000000000001
21
Mean accuracy: 0.6500000000000001
22
Mean accuracy: 0.61
23
Mean accuracy: 0.675
24
Mean accuracy: 0.62
25
Mean accuracy: 0.605
26
Mean accuracy: 0.6100000000000001
27
Mean accuracy: 0.655
28
Mean accuracy: 0.6100000000000001
29
Mean accuracy: 0.6499999999999999
30
Mean accuracy: 0.65
31
Mean accuracy: 0.6100000000000001
32
Mean accuracy: 0.565
33
Mean accuracy: 0.655
34
Mean accuracy: 0.61
35
Mean accuracy: 0.625
36
Mean accuracy: 0.65
37
Mean accuracy: 0.67
38
Mean accuracy: 0.635
39
Mean accuracy: 0.6449999999999999
40
Mean accuracy: 0.6799999999999999
41
Mean accuracy: 0.64
42
Mean accuracy: 0.625
43
Mean accuracy: 0.6450000000000001
44
Mean accuracy: 0.615
45
Mean accuracy: 0.5600000000000002
46
Mean accuracy: 0.665
47
Mean accuracy: 0.6
48
Mean accuracy: 0.66
49
Mean accuracy: 0.5650000000000001
50
Mean accuracy: 0.64
51
Mean accuracy: 0.63
52
Mean accuracy: 0.595
53
Mean accuracy: 0.5850000000000001
54
Mean accuracy: 0.57
55
Mean accuracy: 0.62
56
Mean accuracy: 0.61
57
Mean accuracy: 0.59
58
Mean accuracy: 0.655
59
Mean accuracy: 0.5650000000000001
60
Mean accuracy: 0.585
61
Mean accuracy: 0.55
62
Mean accuracy: 0.6199999999999999
63
Mean accuracy: 0.5349999999999999
64
Mean accuracy: 0.62
65
Mean accuracy: 0.685
66
Mean accuracy: 0.6050000000000001
67
Mean accuracy: 0.635
68
Mean accuracy: 0.635
69
Mean accuracy: 0.5549999999999999
70
Mean accuracy: 0.635
71
Mean accuracy: 0.615
72
Mean accuracy: 0.58
73
Mean accuracy: 0.575
74
Mean accuracy: 0.6
75
Mean accuracy: 0.625
76
Mean accuracy: 0.63
77
Mean accuracy: 0.595
78
Mean accuracy: 0.635
79
Mean accuracy: 0.6449999999999999
80
Mean accuracy: 0.5549999999999999
81
Mean accuracy: 0.635
82
Mean accuracy: 0.59
83
Mean accuracy: 0.625
84
Mean accuracy: 0.5900000000000001
85
Mean accuracy: 0.6250000000000001
86
Mean accuracy: 0.6300000000000001
87
Mean accuracy: 0.5999999999999999
88
Mean accuracy: 0.645
89
Mean accuracy: 0.675
90
Mean accuracy: 0.6300000000000001
91
Mean accuracy: 0.6200000000000001
92
Mean accuracy: 0.62
93
Mean accuracy: 0.635
94
Mean accuracy: 0.5950000000000001
95
Mean accuracy: 0.58
96
Mean accuracy: 0.615
97
Mean accuracy: 0.645
98
Mean accuracy: 0.65
99
Mean accuracy: 0.655
100
Mean accuracy: 0.6

In [7]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("NMI50_DEGs_100RF.csv", index = False)

0.6175499999999999

## Top 100 NMI

In [8]:
df2 = pd.read_csv('NMI_AllCounts.csv')
df2_sub = df2['Geneid'].iloc[:101]
df2_sub.head(2)

0            DIAGNOSIS
1    ENSG00000257878.1
Name: Geneid, dtype: object

In [9]:
df_100 = df1[df2_sub]
print(df_100.shape)
df_100.head(2)

(2110, 101)

,DIAGNOSIS,ENSG00000257878.1,ENSG00000268240.1,ENSG00000111490.13,ENSG00000225873.4,ENSG00000057757.9,ENSG00000152463.14,ENSG00000152484.13,ENSG00000165434.7,ENSG00000173598.13,...,ENSG00000070413.19,ENSG00000135924.15,ENSG00000249763.1,ENSG00000136999.4,ENSG00000285816.1,ENSG00000115590.13,ENSG00000187010.20,ENSG00000179818.13,ENSG00000104892.16,ENSG00000270640.1
0,PD,566,117,228,238,12244,4,6992,1052,7607,...,4698,6382,13,363,159,3205,9,6391,1302,207
1,Control,790,95,258,293,7505,9,5983,1402,4772,...,3080,3456,55,388,114,3274,174,5640,271,201

In [10]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df2 = df_100.groupby('DIAGNOSIS').apply(lambda x: x.sample(100))
    X = df2.drop('DIAGNOSIS', axis = 1)
    y = df2['DIAGNOSIS']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.5850000000000001
2
Mean accuracy: 0.5750000000000001
3
Mean accuracy: 0.5250000000000001
4
Mean accuracy: 0.66
5
Mean accuracy: 0.6
6
Mean accuracy: 0.63
7
Mean accuracy: 0.6
8
Mean accuracy: 0.6250000000000001
9
Mean accuracy: 0.585
10
Mean accuracy: 0.675
11
Mean accuracy: 0.6
12
Mean accuracy: 0.635
13
Mean accuracy: 0.625
14
Mean accuracy: 0.62
15
Mean accuracy: 0.565
16
Mean accuracy: 0.5549999999999999
17
Mean accuracy: 0.5800000000000001
18
Mean accuracy: 0.675
19
Mean accuracy: 0.605
20
Mean accuracy: 0.6
21
Mean accuracy: 0.675
22
Mean accuracy: 0.6199999999999999
23
Mean accuracy: 0.6649999999999999
24
Mean accuracy: 0.655
25
Mean accuracy: 0.6
26
Mean accuracy: 0.625
27
Mean accuracy: 0.62
28
Mean accuracy: 0.55
29
Mean accuracy: 0.615
30
Mean accuracy: 0.6349999999999999
31
Mean accuracy: 0.615
32
Mean accuracy: 0.55
33
Mean accuracy: 0.635
34
Mean accuracy: 0.62
35
Mean accuracy: 0.6250000000000001
36
Mean accuracy: 0.585
37
Mean accuracy: 0.65
38
Mean accuracy: 0.61
39
Mean accuracy: 0.67
40
Mean accuracy: 0.65
41
Mean accuracy: 0.64
42
Mean accuracy: 0.5399999999999999
43
Mean accuracy: 0.6100000000000001
44
Mean accuracy: 0.645
45
Mean accuracy: 0.59
46
Mean accuracy: 0.675
47
Mean accuracy: 0.6300000000000001
48
Mean accuracy: 0.66
49
Mean accuracy: 0.5650000000000001
50
Mean accuracy: 0.61
51
Mean accuracy: 0.645
52
Mean accuracy: 0.6050000000000001
53
Mean accuracy: 0.585
54
Mean accuracy: 0.63
55
Mean accuracy: 0.6100000000000001
56
Mean accuracy: 0.5700000000000001
57
Mean accuracy: 0.595
58
Mean accuracy: 0.655
59
Mean accuracy: 0.5549999999999999
60
Mean accuracy: 0.6100000000000001
61
Mean accuracy: 0.5599999999999998
62
Mean accuracy: 0.64
63
Mean accuracy: 0.52
64
Mean accuracy: 0.65
65
Mean accuracy: 0.655
66
Mean accuracy: 0.58
67
Mean accuracy: 0.5999999999999999
68
Mean accuracy: 0.6599999999999999
69
Mean accuracy: 0.6100000000000001
70
Mean accuracy: 0.635
71
Mean accuracy: 0.64
72
Mean accuracy: 0.5700000000000001
73
Mean accuracy: 0.5650000000000001
74
Mean accuracy: 0.585
75
Mean accuracy: 0.595
76
Mean accuracy: 0.655
77
Mean accuracy: 0.5650000000000001
78
Mean accuracy: 0.645
79
Mean accuracy: 0.62
80
Mean accuracy: 0.5650000000000001
81
Mean accuracy: 0.64
82
Mean accuracy: 0.565
83
Mean accuracy: 0.6450000000000001
84
Mean accuracy: 0.575
85
Mean accuracy: 0.635
86
Mean accuracy: 0.6649999999999999
87
Mean accuracy: 0.6200000000000001
88
Mean accuracy: 0.64
89
Mean accuracy: 0.68
90
Mean accuracy: 0.6399999999999999
91
Mean accuracy: 0.62
92
Mean accuracy: 0.595
93
Mean accuracy: 0.6300000000000001
94
Mean accuracy: 0.625
95
Mean accuracy: 0.645
96
Mean accuracy: 0.595
97
Mean accuracy: 0.655
98
Mean accuracy: 0.635
99
Mean accuracy: 0.6399999999999999
100
Mean accuracy: 0.63

In [11]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("NMI100_DEGs_100RF.csv", index = False)

0.61505

## Top 250 NMI

In [12]:
df2 = pd.read_csv('NMI_AllCounts.csv')
df2_sub = df2['Geneid'].iloc[:251]
df2_sub.head(2)

0            DIAGNOSIS
1    ENSG00000257878.1
Name: Geneid, dtype: object

In [13]:
df_250 = df1[df2_sub]
print(df_250.shape)
df_250.head(2)

(2110, 251)

,DIAGNOSIS,ENSG00000257878.1,ENSG00000268240.1,ENSG00000111490.13,ENSG00000225873.4,ENSG00000057757.9,ENSG00000152463.14,ENSG00000152484.13,ENSG00000165434.7,ENSG00000173598.13,...,ENSG00000006282.20,ENSG00000259674.1,ENSG00000228242.6,ENSG00000285647.1,ENSG00000111859.16,ENSG00000177369.8,ENSG00000238222.3,ENSG00000106537.7,ENSG00000163464.7,ENSG00000132819.16
0,PD,566,117,228,238,12244,4,6992,1052,7607,...,514,33,1344,7,11954,14,26,186,9512,18646
1,Control,790,95,258,293,7505,9,5983,1402,4772,...,363,29,1567,5,8481,22,5,595,11763,6388

In [14]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df2 = df_250.groupby('DIAGNOSIS').apply(lambda x: x.sample(100))
    X = df2.drop('DIAGNOSIS', axis = 1)
    y = df2['DIAGNOSIS']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.5449999999999999
2
Mean accuracy: 0.6
3
Mean accuracy: 0.5850000000000001
4
Mean accuracy: 0.65
5
Mean accuracy: 0.6050000000000001
6
Mean accuracy: 0.63
7
Mean accuracy: 0.595
8
Mean accuracy: 0.6
9
Mean accuracy: 0.595
10
Mean accuracy: 0.675
11
Mean accuracy: 0.595
12
Mean accuracy: 0.615
13
Mean accuracy: 0.615
14
Mean accuracy: 0.62
15
Mean accuracy: 0.5599999999999999
16
Mean accuracy: 0.5650000000000001
17
Mean accuracy: 0.625
18
Mean accuracy: 0.6100000000000001
19
Mean accuracy: 0.61
20
Mean accuracy: 0.6
21
Mean accuracy: 0.65
22
Mean accuracy: 0.595
23
Mean accuracy: 0.685
24
Mean accuracy: 0.6200000000000001
25
Mean accuracy: 0.5850000000000001
26
Mean accuracy: 0.615
27
Mean accuracy: 0.5900000000000001
28
Mean accuracy: 0.5800000000000001
29
Mean accuracy: 0.595
30
Mean accuracy: 0.67
31
Mean accuracy: 0.5999999999999999
32
Mean accuracy: 0.55
33
Mean accuracy: 0.675
34
Mean accuracy: 0.6199999999999999
35
Mean accuracy: 0.64
36
Mean accuracy: 0.585
37
Mean accuracy: 0.62
38
Mean accuracy: 0.635
39
Mean accuracy: 0.64
40
Mean accuracy: 0.6599999999999999
41
Mean accuracy: 0.62
42
Mean accuracy: 0.575
43
Mean accuracy: 0.635
44
Mean accuracy: 0.62
45
Mean accuracy: 0.54
46
Mean accuracy: 0.64
47
Mean accuracy: 0.615
48
Mean accuracy: 0.665
49
Mean accuracy: 0.5599999999999999
50
Mean accuracy: 0.63
51
Mean accuracy: 0.645
52
Mean accuracy: 0.585
53
Mean accuracy: 0.54
54
Mean accuracy: 0.6199999999999999
55
Mean accuracy: 0.65
56
Mean accuracy: 0.615
57
Mean accuracy: 0.605
58
Mean accuracy: 0.6300000000000001
59
Mean accuracy: 0.5599999999999999
60
Mean accuracy: 0.6000000000000001
61
Mean accuracy: 0.6000000000000001
62
Mean accuracy: 0.6300000000000001
63
Mean accuracy: 0.5800000000000001
64
Mean accuracy: 0.6849999999999999
65
Mean accuracy: 0.6500000000000001
66
Mean accuracy: 0.585
67
Mean accuracy: 0.6
68
Mean accuracy: 0.635
69
Mean accuracy: 0.62
70
Mean accuracy: 0.635
71
Mean accuracy: 0.6449999999999999
72
Mean accuracy: 0.58
73
Mean accuracy: 0.55
74
Mean accuracy: 0.5900000000000001
75
Mean accuracy: 0.6
76
Mean accuracy: 0.655
77
Mean accuracy: 0.6199999999999999
78
Mean accuracy: 0.625
79
Mean accuracy: 0.645
80
Mean accuracy: 0.58
81
Mean accuracy: 0.6100000000000001
82
Mean accuracy: 0.52
83
Mean accuracy: 0.6300000000000001
84
Mean accuracy: 0.6150000000000001
85
Mean accuracy: 0.655
86
Mean accuracy: 0.645
87
Mean accuracy: 0.605
88
Mean accuracy: 0.6050000000000001
89
Mean accuracy: 0.6799999999999999
90
Mean accuracy: 0.61
91
Mean accuracy: 0.615
92
Mean accuracy: 0.61
93
Mean accuracy: 0.65
94
Mean accuracy: 0.615
95
Mean accuracy: 0.6249999999999999
96
Mean accuracy: 0.5650000000000001
97
Mean accuracy: 0.64
98
Mean accuracy: 0.6399999999999999
99
Mean accuracy: 0.6399999999999999
100
Mean accuracy: 0.5750000000000001

In [15]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("NMI250_DEGs_100RF.csv", index = False)

0.6131500000000002

## Top 500 NMI

In [16]:
df2 = pd.read_csv('NMI_AllCounts.csv')
df2_sub = df2['Geneid'].iloc[:501]
df2_sub.head(2)

0            DIAGNOSIS
1    ENSG00000257878.1
Name: Geneid, dtype: object

In [17]:
df_500 = df1[df2_sub]
print(df_500.shape)
df_500.head(2)

(2110, 501)

,DIAGNOSIS,ENSG00000257878.1,ENSG00000268240.1,ENSG00000111490.13,ENSG00000225873.4,ENSG00000057757.9,ENSG00000152463.14,ENSG00000152484.13,ENSG00000165434.7,ENSG00000173598.13,...,ENSG00000254087.7,ENSG00000111846.17,ENSG00000156711.16,ENSG00000198919.12,ENSG00000100647.7,ENSG00000187735.13,ENSG00000168016.14,ENSG00000167815.11,ENSG00000146859.6,ENSG00000067182.7
0,PD,566,117,228,238,12244,4,6992,1052,7607,...,18272,1028,1675,1145,3441,5045,22205,3778,6815,3796
1,Control,790,95,258,293,7505,9,5983,1402,4772,...,20234,1040,1110,1824,2620,4597,16399,1358,7383,3450

In [18]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df2 = df_500.groupby('DIAGNOSIS').apply(lambda x: x.sample(100))
    X = df2.drop('DIAGNOSIS', axis = 1)
    y = df2['DIAGNOSIS']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.6
2
Mean accuracy: 0.6
3
Mean accuracy: 0.555
4
Mean accuracy: 0.645
5
Mean accuracy: 0.6100000000000001
6
Mean accuracy: 0.635
7
Mean accuracy: 0.58
8
Mean accuracy: 0.5950000000000001
9
Mean accuracy: 0.605
10
Mean accuracy: 0.6599999999999999
11
Mean accuracy: 0.5349999999999999
12
Mean accuracy: 0.6250000000000001
13
Mean accuracy: 0.6049999999999999
14
Mean accuracy: 0.595
15
Mean accuracy: 0.5750000000000001
16
Mean accuracy: 0.5700000000000001
17
Mean accuracy: 0.6100000000000001
18
Mean accuracy: 0.645
19
Mean accuracy: 0.59
20
Mean accuracy: 0.62
21
Mean accuracy: 0.64
22
Mean accuracy: 0.6
23
Mean accuracy: 0.6399999999999999
24
Mean accuracy: 0.6399999999999999
25
Mean accuracy: 0.5850000000000001
26
Mean accuracy: 0.6
27
Mean accuracy: 0.675
28
Mean accuracy: 0.59
29
Mean accuracy: 0.575
30
Mean accuracy: 0.5999999999999999
31
Mean accuracy: 0.6000000000000001
32
Mean accuracy: 0.5599999999999999
33
Mean accuracy: 0.65
34
Mean accuracy: 0.6200000000000001
35
Mean accuracy: 0.65
36
Mean accuracy: 0.62
37
Mean accuracy: 0.6399999999999999
38
Mean accuracy: 0.645
39
Mean accuracy: 0.64
40
Mean accuracy: 0.63
41
Mean accuracy: 0.62
42
Mean accuracy: 0.525
43
Mean accuracy: 0.5900000000000001
44
Mean accuracy: 0.63
45
Mean accuracy: 0.5900000000000001
46
Mean accuracy: 0.6700000000000002
47
Mean accuracy: 0.635
48
Mean accuracy: 0.655
49
Mean accuracy: 0.555
50
Mean accuracy: 0.655
51
Mean accuracy: 0.625
52
Mean accuracy: 0.625
53
Mean accuracy: 0.55
54
Mean accuracy: 0.5900000000000001
55
Mean accuracy: 0.615
56
Mean accuracy: 0.615
57
Mean accuracy: 0.625
58
Mean accuracy: 0.64
59
Mean accuracy: 0.5399999999999999
60
Mean accuracy: 0.6050000000000001
61
Mean accuracy: 0.55
62
Mean accuracy: 0.6399999999999999
63
Mean accuracy: 0.58
64
Mean accuracy: 0.6450000000000001
65
Mean accuracy: 0.67
66
Mean accuracy: 0.605
67
Mean accuracy: 0.625
68
Mean accuracy: 0.645
69
Mean accuracy: 0.6100000000000001
70
Mean accuracy: 0.62
71
Mean accuracy: 0.635
72
Mean accuracy: 0.575
73
Mean accuracy: 0.55
74
Mean accuracy: 0.63
75
Mean accuracy: 0.6399999999999999
76
Mean accuracy: 0.66
77
Mean accuracy: 0.575
78
Mean accuracy: 0.61
79
Mean accuracy: 0.6500000000000001
80
Mean accuracy: 0.55
81
Mean accuracy: 0.5900000000000001
82
Mean accuracy: 0.495
83
Mean accuracy: 0.6
84
Mean accuracy: 0.61
85
Mean accuracy: 0.62
86
Mean accuracy: 0.6
87
Mean accuracy: 0.61
88
Mean accuracy: 0.6300000000000001
89
Mean accuracy: 0.6699999999999999
90
Mean accuracy: 0.625
91
Mean accuracy: 0.595
92
Mean accuracy: 0.6449999999999999
93
Mean accuracy: 0.625
94
Mean accuracy: 0.595
95
Mean accuracy: 0.565
96
Mean accuracy: 0.61
97
Mean accuracy: 0.6450000000000001
98
Mean accuracy: 0.6599999999999999
99
Mean accuracy: 0.645
100
Mean accuracy: 0.58

In [19]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("NMI500_DEGs_100RF.csv", index = False)

0.6109