# Random Forest Classification

## Importing the libraries

In [1]:
import random
import numpy as np
import pandas as pd
import seaborn as sn
from numpy import std
from numpy import mean
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.metrics import confusion_matrix, accuracy_score
%matplotlib inline

In [2]:
%cd Z:\PPMI_Data\Excel_Data\NonMotors\Feature_CpG_Gene_Association\Constipation_Processed_Files
df = pd.read_csv('ConstipationCateg_Methylome_APPRDXFilter.csv')
print(df.shape)
df.head()

Z:\PPMI_Data\Excel_Data\NonMotors\Feature_CpG_Gene_Association\Constipation_Processed_Files
(458, 20757)

,Sentrix,PATNO,HYS,Gender,APPRDX,MDSP_Constipate,cg13609937,cg13847987,cg13822231,cg20728472,...,cg06819251,cg22158158,cg20161227,cg05701765,cg25437180,cg06002203,cg21722170,cg13142750,cg12743359,cg04293703
0,200991620021_R01C01,3001,2,1,1,0,0.020100,0.922355,0.011956,0.021950,...,0.900701,0.906393,0.948309,0.847871,0.647087,0.836282,0.731078,0.628030,0.883242,0.534427
1,200973410167_R04C01,3007,2,1,1,0,0.071529,0.938088,0.013730,0.029759,...,0.739334,0.888118,0.914366,0.854601,0.685887,0.890144,0.816051,0.735720,0.892971,0.540466
2,200973410167_R05C01,3010,2,1,1,0,0.068068,0.943100,0.013073,0.029993,...,0.795192,0.913136,0.914043,0.797516,0.623537,0.851161,0.849880,0.698082,0.863093,0.568347
3,200989060001_R06C01,3012,2,1,1,1,0.022575,0.949174,0.009046,0.040369,...,0.929675,0.878735,0.949256,0.845943,0.690392,0.892028,0.825284,0.693743,0.865786,0.595054
4,200989060143_R08C01,3024,2,1,1,0,0.010521,0.969717,0.007811,0.016222,...,0.940024,0.935879,0.980890,0.886493,0.655369,0.892382,0.743763,0.738009,0.880286,0.576441

In [3]:
df1 = df.drop(['PATNO', 'Sentrix', 'HYS', 'Gender', 'MDSP_Constipate'], axis=1)
df1.head(2)

,APPRDX,cg13609937,cg13847987,cg13822231,cg20728472,cg14567798,cg14205952,cg13083110,cg24453271,cg18015632,...,cg06819251,cg22158158,cg20161227,cg05701765,cg25437180,cg06002203,cg21722170,cg13142750,cg12743359,cg04293703
0,1,0.020100,0.922355,0.011956,0.021950,0.019629,0.011816,0.531190,0.824585,0.879564,...,0.900701,0.906393,0.948309,0.847871,0.647087,0.836282,0.731078,0.62803,0.883242,0.534427
1,1,0.071529,0.938088,0.013730,0.029759,0.025837,0.013719,0.578083,0.820133,0.892031,...,0.739334,0.888118,0.914366,0.854601,0.685887,0.890144,0.816051,0.73572,0.892971,0.540466

In [4]:
df1 = df1.transpose()
df1.head(2)

,0,1,2,3,4,5,6,7,8,9,...,448,449,450,451,452,453,454,455,456,457
APPRDX,1.0000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0000,1.000000,1.000000,...,2.000000,2.000000,2.000000,2.0000,2.000000,2.000000,2.000000,2.000000,2.00000,2.000000
cg13609937,0.0201,0.071529,0.068068,0.022575,0.010521,0.025196,0.017565,0.0187,0.024127,0.016457,...,0.018173,0.018913,0.018837,0.0176,0.020231,0.016197,0.023998,0.023032,0.02184,0.020266

In [5]:
df1.rename(columns=df1.iloc[0], inplace = True)

In [6]:
df1.index.name ='CpG'
df1.reset_index(inplace=True)
df1.head(2)

,CpG,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
0,APPRDX,1.0000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0000,1.000000,...,2.000000,2.000000,2.000000,2.0000,2.000000,2.000000,2.000000,2.000000,2.00000,2.000000
1,cg13609937,0.0201,0.071529,0.068068,0.022575,0.010521,0.025196,0.017565,0.0187,0.024127,...,0.018173,0.018913,0.018837,0.0176,0.020231,0.016197,0.023998,0.023032,0.02184,0.020266

In [7]:
df1 = df1.drop ([0], axis = 0)
df1.head(2)

,CpG,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
1,cg13609937,0.020100,0.071529,0.068068,0.022575,0.010521,0.025196,0.017565,0.018700,0.024127,...,0.018173,0.018913,0.018837,0.017600,0.020231,0.016197,0.023998,0.023032,0.021840,0.020266
2,cg13847987,0.922355,0.938088,0.943100,0.949174,0.969717,0.958496,0.939032,0.960726,0.935071,...,0.943517,0.959274,0.955007,0.967183,0.963796,0.968448,0.970054,0.940215,0.927902,0.933645

In [8]:
df2 = pd.read_csv ("Constipation_NMI_Top50.csv")
df2.head(2)

          CpG
0  cg27281389
1  cg21899921

In [9]:
df3 = pd.merge (df1, df2, on= "CpG", how= "inner")
df3.head(2)

,CpG,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
0,cg13605579,0.863394,0.893290,0.887179,0.928351,0.922917,0.920281,0.92676,0.928217,0.907251,...,0.921057,0.926983,0.915528,0.917486,0.891751,0.918448,0.915208,0.916855,0.922400,0.921273
1,cg25410117,0.133229,0.090223,0.067516,0.073282,0.063792,0.072253,0.05435,0.053401,0.077231,...,0.062620,0.110247,0.117870,0.044926,0.090360,0.074899,0.107529,0.119025,0.098492,0.079300

In [10]:
df3 = df3.transpose()
df3.head(2)

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
CpG,cg13605579,cg25410117,cg10688123,cg13332222,cg23786063,cg20349377,cg25210047,cg10044815,cg12298429,cg27281389,...,cg12036621,cg26801812,cg09068129,cg06425631,cg05142211,cg11549065,cg17458425,cg10783204,cg08096908,cg24224407
1.0,0.863394,0.133229,0.833705,0.902238,0.889644,0.876278,0.827441,0.894322,0.032801,0.026921,...,0.030171,0.847042,0.852115,0.932296,0.035018,0.032903,0.856462,0.585492,0.905542,0.87535

In [11]:
df3.rename(columns=df3.iloc[0], inplace = True)

In [12]:
df3.index.name ='APPRDX'
df3.reset_index(inplace=True)
df3.head(2)

,APPRDX,cg13605579,cg25410117,cg10688123,cg13332222,cg23786063,cg20349377,cg25210047,cg10044815,cg12298429,...,cg12036621,cg26801812,cg09068129,cg06425631,cg05142211,cg11549065,cg17458425,cg10783204,cg08096908,cg24224407
0,CpG,cg13605579,cg25410117,cg10688123,cg13332222,cg23786063,cg20349377,cg25210047,cg10044815,cg12298429,...,cg12036621,cg26801812,cg09068129,cg06425631,cg05142211,cg11549065,cg17458425,cg10783204,cg08096908,cg24224407
1,1.0,0.863394,0.133229,0.833705,0.902238,0.889644,0.876278,0.827441,0.894322,0.032801,...,0.030171,0.847042,0.852115,0.932296,0.035018,0.032903,0.856462,0.585492,0.905542,0.87535

In [13]:
df3 = df3.drop ([0], axis = 0)
df3.head(2)

,APPRDX,cg13605579,cg25410117,cg10688123,cg13332222,cg23786063,cg20349377,cg25210047,cg10044815,cg12298429,...,cg12036621,cg26801812,cg09068129,cg06425631,cg05142211,cg11549065,cg17458425,cg10783204,cg08096908,cg24224407
1,1.0,0.863394,0.133229,0.833705,0.902238,0.889644,0.876278,0.827441,0.894322,0.032801,...,0.030171,0.847042,0.852115,0.932296,0.035018,0.032903,0.856462,0.585492,0.905542,0.87535
2,1.0,0.89329,0.090223,0.861144,0.928699,0.893976,0.89381,0.804296,0.902732,0.042715,...,0.033681,0.817918,0.819744,0.930258,0.041906,0.043359,0.908599,0.654016,0.918975,0.867527

In [14]:
df3.reset_index(inplace = True, drop = True)
df3.head()

,APPRDX,cg13605579,cg25410117,cg10688123,cg13332222,cg23786063,cg20349377,cg25210047,cg10044815,cg12298429,...,cg12036621,cg26801812,cg09068129,cg06425631,cg05142211,cg11549065,cg17458425,cg10783204,cg08096908,cg24224407
0,1.0,0.863394,0.133229,0.833705,0.902238,0.889644,0.876278,0.827441,0.894322,0.032801,...,0.030171,0.847042,0.852115,0.932296,0.035018,0.032903,0.856462,0.585492,0.905542,0.87535
1,1.0,0.89329,0.090223,0.861144,0.928699,0.893976,0.89381,0.804296,0.902732,0.042715,...,0.033681,0.817918,0.819744,0.930258,0.041906,0.043359,0.908599,0.654016,0.918975,0.867527
2,1.0,0.887179,0.067516,0.805015,0.914653,0.893268,0.894644,0.777569,0.88532,0.033475,...,0.032915,0.776999,0.828306,0.932535,0.019257,0.049133,0.903632,0.592993,0.923476,0.859168
3,1.0,0.928351,0.073282,0.876215,0.937166,0.944431,0.940694,0.908748,0.937065,0.032138,...,0.021967,0.888903,0.887458,0.951873,0.018673,0.051667,0.880323,0.729795,0.946482,0.907303
4,1.0,0.922917,0.063792,0.782054,0.924741,0.923256,0.924065,0.808504,0.927527,0.030728,...,0.021042,0.875846,0.828259,0.93951,0.024418,0.036073,0.901781,0.740307,0.917266,0.897316

In [15]:
df3.shape

(458, 51)

In [16]:
df3 ['APPRDX'] = df3 ['APPRDX'].apply(int)

## RanFor 1000 times, CpG only

In [17]:
df3.head(2)

,APPRDX,cg13605579,cg25410117,cg10688123,cg13332222,cg23786063,cg20349377,cg25210047,cg10044815,cg12298429,...,cg12036621,cg26801812,cg09068129,cg06425631,cg05142211,cg11549065,cg17458425,cg10783204,cg08096908,cg24224407
0,1,0.863394,0.133229,0.833705,0.902238,0.889644,0.876278,0.827441,0.894322,0.032801,...,0.030171,0.847042,0.852115,0.932296,0.035018,0.032903,0.856462,0.585492,0.905542,0.87535
1,1,0.89329,0.090223,0.861144,0.928699,0.893976,0.89381,0.804296,0.902732,0.042715,...,0.033681,0.817918,0.819744,0.930258,0.041906,0.043359,0.908599,0.654016,0.918975,0.867527

In [18]:
df3.shape

(458, 51)

In [ ]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,1001) :
        print(i)
        dataset = df3.groupby('APPRDX').apply(lambda x: x.sample(100))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=1, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250

In [ ]:
dframe1.to_csv ("Constipation_NMITop50CpG_Accuracy_1000RF.csv")

In [ ]:
dframe1.head(2)