In [1]:
import pandas as pd
import numpy as np

In [2]:
%cd Z:\PPMI_Data\Excel_Data\Raw_And_More
df = pd.read_csv ("beta_post_Funnorm_PPMI_EPICn524final030618.csv")
df = df.round(decimals = 4)
df.head(2)

Z:\PPMI_Data\Excel_Data\Raw_And_More

,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,200973410167_R05C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
cg14817997,0.8340,0.8492,0.7730,0.8853,0.7725,0.7564,0.7198,0.7759,0.7689,0.7594,...,0.7882,0.8389,0.8453,0.7704,0.8529,0.7838,0.8069,0.8757,0.6613,0.7379
cg26928153,0.9456,0.9485,0.9622,0.9440,0.9263,0.9561,0.9130,0.9560,0.9571,0.8976,...,0.9512,0.9590,0.9571,0.9547,0.9478,0.9581,0.9480,0.9424,0.9550,0.9463

In [3]:
df.index.name ='CpG'
df.reset_index(inplace=True)
df.head(2)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg14817997,0.8340,0.8492,0.7730,0.8853,0.7725,0.7564,0.7198,0.7759,0.7689,...,0.7882,0.8389,0.8453,0.7704,0.8529,0.7838,0.8069,0.8757,0.6613,0.7379
1,cg26928153,0.9456,0.9485,0.9622,0.9440,0.9263,0.9561,0.9130,0.9560,0.9571,...,0.9512,0.9590,0.9571,0.9547,0.9478,0.9581,0.9480,0.9424,0.9550,0.9463

In [4]:
dframe = pd.read_csv ('CpG_AboveNMI.04_AllChrin_APP1vs2.csv')
dframe.head(2)

          CpG
0  cg10991923
1  cg16881640

In [5]:
dfMerge = pd.merge (df, dframe, on= "CpG", how= "inner")
dfMerge.head(2)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg03648020,0.3990,0.4261,0.3351,0.3155,0.3322,0.5129,0.4077,0.4496,0.5488,...,0.3403,0.4396,0.4874,0.2448,0.2754,0.4964,0.5017,0.6454,0.4292,0.5810
1,cg01354137,0.9247,0.8509,0.9072,0.8789,0.8563,0.8803,0.9124,0.8850,0.8520,...,0.8839,0.8758,0.8744,0.8917,0.8540,0.8691,0.8920,0.8970,0.9038,0.9208

In [6]:
dft = dfMerge.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,609,610,611,612,613,614,615,616,617,618
CpG,cg03648020,cg01354137,cg23022057,cg20433829,cg11504517,cg00737943,cg11185792,cg11027230,cg09042458,cg00894481,...,cg11882967,cg15563580,cg07940547,cg03244736,cg03518176,cg16795639,cg06174815,cg25852925,cg10538243,cg16951920
200973410159_R03C01,0.399,0.9247,0.8816,0.9201,0.1493,0.913,0.2222,0.9245,0.9316,0.7124,...,0.9187,0.652,0.4363,0.5485,0.845,0.7072,0.2913,0.4827,0.6033,0.8305

In [7]:
dft.rename(columns=dft.iloc[0], inplace = True)

In [8]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg03648020,cg01354137,cg23022057,cg20433829,cg11504517,cg00737943,cg11185792,cg11027230,cg09042458,...,cg11882967,cg15563580,cg07940547,cg03244736,cg03518176,cg16795639,cg06174815,cg25852925,cg10538243,cg16951920
0,CpG,cg03648020,cg01354137,cg23022057,cg20433829,cg11504517,cg00737943,cg11185792,cg11027230,cg09042458,...,cg11882967,cg15563580,cg07940547,cg03244736,cg03518176,cg16795639,cg06174815,cg25852925,cg10538243,cg16951920
1,200973410159_R03C01,0.399,0.9247,0.8816,0.9201,0.1493,0.913,0.2222,0.9245,0.9316,...,0.9187,0.652,0.4363,0.5485,0.845,0.7072,0.2913,0.4827,0.6033,0.8305

In [9]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg03648020,cg01354137,cg23022057,cg20433829,cg11504517,cg00737943,cg11185792,cg11027230,cg09042458,...,cg11882967,cg15563580,cg07940547,cg03244736,cg03518176,cg16795639,cg06174815,cg25852925,cg10538243,cg16951920
1,200973410159_R03C01,0.399,0.9247,0.8816,0.9201,0.1493,0.913,0.2222,0.9245,0.9316,...,0.9187,0.652,0.4363,0.5485,0.845,0.7072,0.2913,0.4827,0.6033,0.8305
2,200991620021_R01C01,0.4261,0.8509,0.8888,0.91,0.2712,0.83,0.1466,0.8711,0.8843,...,0.8939,0.7782,0.6529,0.5532,0.8265,0.4879,0.0482,0.1089,0.2662,0.8771

In [10]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg03648020,cg01354137,cg23022057,cg20433829,cg11504517,cg00737943,cg11185792,cg11027230,cg09042458,...,cg11882967,cg15563580,cg07940547,cg03244736,cg03518176,cg16795639,cg06174815,cg25852925,cg10538243,cg16951920
1,200973410159_R03C01,0.399,0.9247,0.8816,0.9201,0.1493,0.913,0.2222,0.9245,0.9316,...,0.9187,0.652,0.4363,0.5485,0.845,0.7072,0.2913,0.4827,0.6033,0.8305
2,200991620021_R01C01,0.4261,0.8509,0.8888,0.91,0.2712,0.83,0.1466,0.8711,0.8843,...,0.8939,0.7782,0.6529,0.5532,0.8265,0.4879,0.0482,0.1089,0.2662,0.8771

In [11]:
df2 = pd.read_csv ("Comm10FeatData_withBasicDetails.csv")
df2.head(2)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,MDS_Depress,MDSP_Constipate,MDSP_Fatigue,MDSP_LightHead,MDSP_SleepDay,MDSP_Pain,Montreal_Cognitive,SCOPA_Sex,Symbol_Digit,UPSIT_3
0,200973410159_R03C01,3000,2,2,0,69.1,4,1,0,0,0,1,0,0,0,0,0
1,200991620021_R01C01,3001,1,1,2,65.1,4,0,0,1,0,1,0,0,2,1,1

In [12]:
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
df3.head(2)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,MDS_Depress,MDSP_Constipate,MDSP_Fatigue,...,cg11882967,cg15563580,cg07940547,cg03244736,cg03518176,cg16795639,cg06174815,cg25852925,cg10538243,cg16951920
0,200973410159_R03C01,3000,2,2,0,69.1,4,1,0,0,...,0.9187,0.652,0.4363,0.5485,0.845,0.7072,0.2913,0.4827,0.6033,0.8305
1,200991620021_R01C01,3001,1,1,2,65.1,4,0,0,1,...,0.8939,0.7782,0.6529,0.5532,0.8265,0.4879,0.0482,0.1089,0.2662,0.8771

In [13]:
df3.shape

(457, 636)

In [14]:
df3.to_csv ("CpG_AboveNMI.04inAllChr_withComm10FeatData_withMethylDetail.csv", index = False)