# Random Forest Classification

In [1]:
import random
import numpy as np
import pandas as pd
import seaborn as sn
from numpy import std
from numpy import mean
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.metrics import confusion_matrix, accuracy_score
%matplotlib inline

## Top 50 Boruta

In [2]:
%cd S:\PPMI_RNA\Processed\Male
df = pd.read_csv('DEGs_Boruta_Top50_Data_Male.csv')
print(df.shape)
df.head(2)

S:\PPMI_RNA\Processed\Male
(1346, 51)

,DIAGNOSIS,ENSG00000189337.16,ENSG00000076864.19,ENSG00000187010.20,ENSG00000222112.1,ENSG00000273136.6,ENSG00000281741.2,ENSG00000226067.6,ENSG00000263961.7,ENSG00000135778.11,...,ENSG00000258831.1,ENSG00000262332.1,ENSG00000167434.9,ENSG00000280096.1,ENSG00000268240.1,ENSG00000268278.1,ENSG00000225178.5,ENSG00000100116.16,ENSG00000238222.3,ENSG00000257696.1
0,1,359,1653,9,544,2592,88,776,55,1500,...,67,61,391,68,117,19,188,278,26,43
1,1,197,61,0,672,6702,22,489,96,1465,...,116,109,446,23,64,12,1137,76,9,46

In [3]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df1 = df.groupby('DIAGNOSIS').apply(lambda x: x.sample(100))
    X = df1.drop('DIAGNOSIS', axis = 1)
    y = df1['DIAGNOSIS']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.65
2
Mean accuracy: 0.645
3
Mean accuracy: 0.685
4
Mean accuracy: 0.6599999999999999
5
Mean accuracy: 0.6100000000000001
6
Mean accuracy: 0.645
7
Mean accuracy: 0.64
8
Mean accuracy: 0.6449999999999999
9
Mean accuracy: 0.58
10
Mean accuracy: 0.62
11
Mean accuracy: 0.57
12
Mean accuracy: 0.7
13
Mean accuracy: 0.6300000000000001
14
Mean accuracy: 0.62
15
Mean accuracy: 0.665
16
Mean accuracy: 0.625
17
Mean accuracy: 0.6599999999999999
18
Mean accuracy: 0.6950000000000001
19
Mean accuracy: 0.6199999999999999
20
Mean accuracy: 0.63
21
Mean accuracy: 0.6449999999999999
22
Mean accuracy: 0.69
23
Mean accuracy: 0.63
24
Mean accuracy: 0.665
25
Mean accuracy: 0.6100000000000001
26
Mean accuracy: 0.7150000000000001
27
Mean accuracy: 0.695
28
Mean accuracy: 0.67
29
Mean accuracy: 0.6699999999999999
30
Mean accuracy: 0.615
31
Mean accuracy: 0.7150000000000001
32
Mean accuracy: 0.625
33
Mean accuracy: 0.615
34
Mean accuracy: 0.7000000000000001
35
Mean accuracy: 0.63
36
Mean accuracy: 0.615
37
Mean accuracy: 0.67
38
Mean accuracy: 0.685
39
Mean accuracy: 0.67
40
Mean accuracy: 0.66
41
Mean accuracy: 0.61
42
Mean accuracy: 0.6399999999999999
43
Mean accuracy: 0.63
44
Mean accuracy: 0.6
45
Mean accuracy: 0.7050000000000001
46
Mean accuracy: 0.68
47
Mean accuracy: 0.74
48
Mean accuracy: 0.6699999999999999
49
Mean accuracy: 0.6950000000000001
50
Mean accuracy: 0.6699999999999999
51
Mean accuracy: 0.625
52
Mean accuracy: 0.6950000000000001
53
Mean accuracy: 0.665
54
Mean accuracy: 0.66
55
Mean accuracy: 0.6849999999999999
56
Mean accuracy: 0.655
57
Mean accuracy: 0.68
58
Mean accuracy: 0.695
59
Mean accuracy: 0.605
60
Mean accuracy: 0.66
61
Mean accuracy: 0.745
62
Mean accuracy: 0.655
63
Mean accuracy: 0.6900000000000001
64
Mean accuracy: 0.6399999999999999
65
Mean accuracy: 0.675
66
Mean accuracy: 0.65
67
Mean accuracy: 0.625
68
Mean accuracy: 0.6249999999999999
69
Mean accuracy: 0.64
70
Mean accuracy: 0.6799999999999999
71
Mean accuracy: 0.635
72
Mean accuracy: 0.6950000000000001
73
Mean accuracy: 0.645
74
Mean accuracy: 0.6500000000000001
75
Mean accuracy: 0.635
76
Mean accuracy: 0.715
77
Mean accuracy: 0.635
78
Mean accuracy: 0.61
79
Mean accuracy: 0.63
80
Mean accuracy: 0.6699999999999999
81
Mean accuracy: 0.6599999999999999
82
Mean accuracy: 0.63
83
Mean accuracy: 0.64
84
Mean accuracy: 0.6900000000000001
85
Mean accuracy: 0.575
86
Mean accuracy: 0.645
87
Mean accuracy: 0.5900000000000001
88
Mean accuracy: 0.635
89
Mean accuracy: 0.5700000000000001
90
Mean accuracy: 0.635
91
Mean accuracy: 0.6599999999999999
92
Mean accuracy: 0.63
93
Mean accuracy: 0.64
94
Mean accuracy: 0.6099999999999999
95
Mean accuracy: 0.62
96
Mean accuracy: 0.645
97
Mean accuracy: 0.6649999999999999
98
Mean accuracy: 0.645
99
Mean accuracy: 0.65
100
Mean accuracy: 0.62

In [4]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("Boruta50_DEGs_Male_100RF.csv", index = False)

0.6505

## Top 100 Boruta

In [5]:
%cd S:\PPMI_RNA\Processed\Male
df = pd.read_csv('DEGs_Boruta_Top100_Data_Male.csv')
print(df.shape)
df.head(2)

S:\PPMI_RNA\Processed\Male
(1346, 101)

,DIAGNOSIS,ENSG00000189337.16,ENSG00000076864.19,ENSG00000187010.20,ENSG00000222112.1,ENSG00000116983.12,ENSG00000173212.4,ENSG00000273136.6,ENSG00000281741.2,ENSG00000226067.6,...,ENSG00000225178.5,ENSG00000186431.18,ENSG00000105048.16,ENSG00000222365.1,ENSG00000100218.11,ENSG00000189060.5,ENSG00000100116.16,ENSG00000238222.3,ENSG00000275063.1,ENSG00000102010.14
0,1,359,1653,9,544,392,104,2592,88,776,...,188,1520,181,251,48,1149,278,26,82,275
1,1,197,61,0,672,270,74,6702,22,489,...,1137,1603,88,242,46,441,76,9,2,361

In [6]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df1 = df.groupby('DIAGNOSIS').apply(lambda x: x.sample(100))
    X = df1.drop('DIAGNOSIS', axis = 1)
    y = df1['DIAGNOSIS']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.665
2
Mean accuracy: 0.625
3
Mean accuracy: 0.6799999999999999
4
Mean accuracy: 0.6499999999999999
5
Mean accuracy: 0.625
6
Mean accuracy: 0.705
7
Mean accuracy: 0.65
8
Mean accuracy: 0.6499999999999999
9
Mean accuracy: 0.615
10
Mean accuracy: 0.61
11
Mean accuracy: 0.68
12
Mean accuracy: 0.6799999999999999
13
Mean accuracy: 0.6200000000000001
14
Mean accuracy: 0.645
15
Mean accuracy: 0.71
16
Mean accuracy: 0.6300000000000001
17
Mean accuracy: 0.71
18
Mean accuracy: 0.695
19
Mean accuracy: 0.6749999999999999
20
Mean accuracy: 0.67
21
Mean accuracy: 0.635
22
Mean accuracy: 0.675
23
Mean accuracy: 0.69
24
Mean accuracy: 0.69
25
Mean accuracy: 0.6799999999999999
26
Mean accuracy: 0.6849999999999999
27
Mean accuracy: 0.715
28
Mean accuracy: 0.665
29
Mean accuracy: 0.655
30
Mean accuracy: 0.6450000000000001
31
Mean accuracy: 0.74
32
Mean accuracy: 0.66
33
Mean accuracy: 0.63
34
Mean accuracy: 0.685
35
Mean accuracy: 0.64
36
Mean accuracy: 0.6699999999999999
37
Mean accuracy: 0.7
38
Mean accuracy: 0.6500000000000001
39
Mean accuracy: 0.7
40
Mean accuracy: 0.7
41
Mean accuracy: 0.6499999999999999
42
Mean accuracy: 0.625
43
Mean accuracy: 0.675
44
Mean accuracy: 0.6500000000000001
45
Mean accuracy: 0.74
46
Mean accuracy: 0.7
47
Mean accuracy: 0.7050000000000001
48
Mean accuracy: 0.685
49
Mean accuracy: 0.72
50
Mean accuracy: 0.665
51
Mean accuracy: 0.6549999999999999
52
Mean accuracy: 0.6799999999999999
53
Mean accuracy: 0.65
54
Mean accuracy: 0.65
55
Mean accuracy: 0.66
56
Mean accuracy: 0.6699999999999999
57
Mean accuracy: 0.705
58
Mean accuracy: 0.7
59
Mean accuracy: 0.6799999999999999
60
Mean accuracy: 0.6599999999999999
61
Mean accuracy: 0.7350000000000001
62
Mean accuracy: 0.61
63
Mean accuracy: 0.675
64
Mean accuracy: 0.6450000000000001
65
Mean accuracy: 0.665
66
Mean accuracy: 0.6699999999999999
67
Mean accuracy: 0.6699999999999999
68
Mean accuracy: 0.67
69
Mean accuracy: 0.665
70
Mean accuracy: 0.6549999999999999
71
Mean accuracy: 0.6249999999999999
72
Mean accuracy: 0.64
73
Mean accuracy: 0.68
74
Mean accuracy: 0.6849999999999999
75
Mean accuracy: 0.6799999999999999
76
Mean accuracy: 0.705
77
Mean accuracy: 0.635
78
Mean accuracy: 0.595
79
Mean accuracy: 0.6249999999999999
80
Mean accuracy: 0.7
81
Mean accuracy: 0.6599999999999999
82
Mean accuracy: 0.64
83
Mean accuracy: 0.655
84
Mean accuracy: 0.72
85
Mean accuracy: 0.5900000000000001
86
Mean accuracy: 0.65
87
Mean accuracy: 0.605
88
Mean accuracy: 0.6299999999999999
89
Mean accuracy: 0.63
90
Mean accuracy: 0.585
91
Mean accuracy: 0.665
92
Mean accuracy: 0.54
93
Mean accuracy: 0.6799999999999999
94
Mean accuracy: 0.64
95
Mean accuracy: 0.6100000000000001
96
Mean accuracy: 0.7250000000000001
97
Mean accuracy: 0.6399999999999999
98
Mean accuracy: 0.6500000000000001
99
Mean accuracy: 0.6399999999999999
100
Mean accuracy: 0.6799999999999999

In [7]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("Boruta100_DEGs_Male_100RF.csv", index = False)

0.6628999999999999

## Top 250 Boruta

In [8]:
%cd S:\PPMI_RNA\Processed\Male
df = pd.read_csv('DEGs_Boruta_Top250_Data_Male.csv')
print(df.shape)
df.head(2)

S:\PPMI_RNA\Processed\Male
(1346, 250)

,DIAGNOSIS,ENSG00000189337.16,ENSG00000142794.18,ENSG00000076864.19,ENSG00000187010.20,ENSG00000159023.21,ENSG00000134686.18,ENSG00000222112.1,ENSG00000116983.12,ENSG00000199377.1,...,ENSG00000184792.15,ENSG00000189060.5,ENSG00000100116.16,ENSG00000102010.14,ENSG00000169891.17,ENSG00000241886.1,ENSG00000238222.3,ENSG00000157514.16,ENSG00000130830.14,ENSG00000275063.1
0,1,359,880,1653,9,147789,3026,544,392,25,...,4312,1149,278,275,5104,449,26,7394,25655,82
1,1,197,407,61,0,51779,3395,672,270,17,...,981,441,76,361,7006,827,9,6408,11059,2

In [9]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df1 = df.groupby('DIAGNOSIS').apply(lambda x: x.sample(100))
    X = df1.drop('DIAGNOSIS', axis = 1)
    y = df1['DIAGNOSIS']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.7
2
Mean accuracy: 0.6
3
Mean accuracy: 0.6849999999999999
4
Mean accuracy: 0.63
5
Mean accuracy: 0.6
6
Mean accuracy: 0.6599999999999999
7
Mean accuracy: 0.595
8
Mean accuracy: 0.66
9
Mean accuracy: 0.595
10
Mean accuracy: 0.62
11
Mean accuracy: 0.64
12
Mean accuracy: 0.705
13
Mean accuracy: 0.635
14
Mean accuracy: 0.665
15
Mean accuracy: 0.72
16
Mean accuracy: 0.66
17
Mean accuracy: 0.675
18
Mean accuracy: 0.68
19
Mean accuracy: 0.6849999999999999
20
Mean accuracy: 0.685
21
Mean accuracy: 0.6500000000000001
22
Mean accuracy: 0.6799999999999999
23
Mean accuracy: 0.645
24
Mean accuracy: 0.695
25
Mean accuracy: 0.645
26
Mean accuracy: 0.7
27
Mean accuracy: 0.69
28
Mean accuracy: 0.6499999999999999
29
Mean accuracy: 0.675
30
Mean accuracy: 0.63
31
Mean accuracy: 0.67
32
Mean accuracy: 0.6450000000000001
33
Mean accuracy: 0.595
34
Mean accuracy: 0.705
35
Mean accuracy: 0.6649999999999999
36
Mean accuracy: 0.6700000000000002
37
Mean accuracy: 0.665
38
Mean accuracy: 0.645
39
Mean accuracy: 0.67
40
Mean accuracy: 0.6749999999999999
41
Mean accuracy: 0.63
42
Mean accuracy: 0.615
43
Mean accuracy: 0.645
44
Mean accuracy: 0.655
45
Mean accuracy: 0.7150000000000001
46
Mean accuracy: 0.7300000000000001
47
Mean accuracy: 0.7150000000000001
48
Mean accuracy: 0.64
49
Mean accuracy: 0.725
50
Mean accuracy: 0.635
51
Mean accuracy: 0.6599999999999999
52
Mean accuracy: 0.7050000000000001
53
Mean accuracy: 0.655
54
Mean accuracy: 0.65
55
Mean accuracy: 0.6900000000000001
56
Mean accuracy: 0.6700000000000002
57
Mean accuracy: 0.635
58
Mean accuracy: 0.6799999999999999
59
Mean accuracy: 0.68
60
Mean accuracy: 0.6449999999999999
61
Mean accuracy: 0.7249999999999999
62
Mean accuracy: 0.6200000000000001
63
Mean accuracy: 0.6849999999999999
64
Mean accuracy: 0.675
65
Mean accuracy: 0.6950000000000001
66
Mean accuracy: 0.64
67
Mean accuracy: 0.6249999999999999
68
Mean accuracy: 0.6849999999999999
69
Mean accuracy: 0.685
70
Mean accuracy: 0.6749999999999999
71
Mean accuracy: 0.6500000000000001
72
Mean accuracy: 0.635
73
Mean accuracy: 0.71
74
Mean accuracy: 0.6350000000000001
75
Mean accuracy: 0.73
76
Mean accuracy: 0.6849999999999999
77
Mean accuracy: 0.6599999999999999
78
Mean accuracy: 0.6399999999999999
79
Mean accuracy: 0.6199999999999999
80
Mean accuracy: 0.6950000000000001
81
Mean accuracy: 0.6849999999999999
82
Mean accuracy: 0.6699999999999999
83
Mean accuracy: 0.62
84
Mean accuracy: 0.6799999999999999
85
Mean accuracy: 0.595
86
Mean accuracy: 0.7
87
Mean accuracy: 0.6100000000000001
88
Mean accuracy: 0.625
89
Mean accuracy: 0.655
90
Mean accuracy: 0.6449999999999999
91
Mean accuracy: 0.6599999999999999
92
Mean accuracy: 0.635
93
Mean accuracy: 0.66
94
Mean accuracy: 0.6500000000000001
95
Mean accuracy: 0.6100000000000001
96
Mean accuracy: 0.6599999999999999
97
Mean accuracy: 0.67
98
Mean accuracy: 0.615
99
Mean accuracy: 0.645
100
Mean accuracy: 0.675

In [10]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("Boruta250_DEGs_Male_100RF.csv", index = False)

0.6606999999999996

## Top 500 Boruta

In [11]:
df = pd.read_csv('All_Counts_PatAndHealthy_Disease_Male.csv')
print(df.shape)
df.head(2)

(1346, 58783)

,HudAlphaID,DIAGNOSIS,PATNO,ENSG00000223972.5,ENSG00000227232.5,ENSG00000278267.1,ENSG00000243485.5,ENSG00000284332.1,ENSG00000237613.2,ENSG00000268020.3,...,ENSG00000273739.1,ENSG00000276700.1,ENSG00000276312.1,ENSG00000275757.1,ENSG00000278573.1,ENSG00000276017.1,ENSG00000278817.1,ENSG00000277196.4,ENSG00000278625.1,ENSG00000277374.1
0,5104_SL_0001,PD,3174,15,232,15,0,0,0,0,...,0,1,16,1,0,2,19,0,0,0
1,5104_SL_0007,PD,3471,0,97,8,0,0,0,0,...,0,9,0,1,0,0,7,1,0,0

In [12]:
df = df.drop(['HudAlphaID' ,'PATNO'], axis=1)
df.head(2)

,DIAGNOSIS,ENSG00000223972.5,ENSG00000227232.5,ENSG00000278267.1,ENSG00000243485.5,ENSG00000284332.1,ENSG00000237613.2,ENSG00000268020.3,ENSG00000240361.2,ENSG00000186092.6,...,ENSG00000273739.1,ENSG00000276700.1,ENSG00000276312.1,ENSG00000275757.1,ENSG00000278573.1,ENSG00000276017.1,ENSG00000278817.1,ENSG00000277196.4,ENSG00000278625.1,ENSG00000277374.1
0,PD,15,232,15,0,0,0,0,0,0,...,0,1,16,1,0,2,19,0,0,0
1,PD,0,97,8,0,0,0,0,0,2,...,0,9,0,1,0,0,7,1,0,0

In [18]:
df2 = pd.read_csv('DEGs_Boruta_All_Male.csv')
df2_sub = df2['CpG'].iloc[:501]
df2_sub.head(3)

0            DIAGNOSIS
1    ENSG00000167434.9
2    ENSG00000257878.1
Name: CpG, dtype: object

In [19]:
df_500 = df[df2_sub]
print(df_500.shape)
df_500.head(2)

(1346, 501)

,DIAGNOSIS,ENSG00000167434.9,ENSG00000257878.1,ENSG00000226752.9,ENSG00000226278.1,ENSG00000135778.11,ENSG00000280096.1,ENSG00000242887.1,ENSG00000163751.3,ENSG00000145244.11,...,ENSG00000251379.1,ENSG00000211753.4,ENSG00000007968.6,ENSG00000179909.15,ENSG00000137642.12,ENSG00000167483.17,ENSG00000211699.2,ENSG00000197766.7,ENSG00000157483.8,ENSG00000232334.1
0,PD,391,566,6424,0,1500,68,57,117,167,...,214,213,4105,2599,124986,1353,176,2856,789,526
1,PD,446,1077,1418,0,1465,23,67,371,35,...,154,16,1075,651,138746,3750,17,3476,816,521

In [20]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df2 = df_500.groupby('DIAGNOSIS').apply(lambda x: x.sample(100))
    X = df2.drop('DIAGNOSIS', axis = 1)
    y = df2['DIAGNOSIS']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.675
2
Mean accuracy: 0.655
3
Mean accuracy: 0.6649999999999999
4
Mean accuracy: 0.6449999999999999
5
Mean accuracy: 0.5700000000000001
6
Mean accuracy: 0.63
7
Mean accuracy: 0.615
8
Mean accuracy: 0.61
9
Mean accuracy: 0.5750000000000001
10
Mean accuracy: 0.5850000000000001
11
Mean accuracy: 0.6100000000000001
12
Mean accuracy: 0.675
13
Mean accuracy: 0.6100000000000001
14
Mean accuracy: 0.675
15
Mean accuracy: 0.6950000000000001
16
Mean accuracy: 0.635
17
Mean accuracy: 0.645
18
Mean accuracy: 0.685
19
Mean accuracy: 0.635
20
Mean accuracy: 0.6599999999999999
21
Mean accuracy: 0.635
22
Mean accuracy: 0.6799999999999999
23
Mean accuracy: 0.65
24
Mean accuracy: 0.675
25
Mean accuracy: 0.595
26
Mean accuracy: 0.69
27
Mean accuracy: 0.6799999999999999
28
Mean accuracy: 0.6250000000000001
29
Mean accuracy: 0.6849999999999999
30
Mean accuracy: 0.615
31
Mean accuracy: 0.68
32
Mean accuracy: 0.595
33
Mean accuracy: 0.5700000000000001
34
Mean accuracy: 0.69
35
Mean accuracy: 0.64
36
Mean accuracy: 0.6849999999999999
37
Mean accuracy: 0.6499999999999999
38
Mean accuracy: 0.5999999999999999
39
Mean accuracy: 0.645
40
Mean accuracy: 0.6399999999999999
41
Mean accuracy: 0.635
42
Mean accuracy: 0.655
43
Mean accuracy: 0.65
44
Mean accuracy: 0.655
45
Mean accuracy: 0.6799999999999999
46
Mean accuracy: 0.675
47
Mean accuracy: 0.6900000000000001
48
Mean accuracy: 0.635
49
Mean accuracy: 0.6950000000000001
50
Mean accuracy: 0.625
51
Mean accuracy: 0.65
52
Mean accuracy: 0.6800000000000002
53
Mean accuracy: 0.655
54
Mean accuracy: 0.635
55
Mean accuracy: 0.6950000000000001
56
Mean accuracy: 0.6649999999999999
57
Mean accuracy: 0.65
58
Mean accuracy: 0.7000000000000001
59
Mean accuracy: 0.6399999999999999
60
Mean accuracy: 0.63
61
Mean accuracy: 0.75
62
Mean accuracy: 0.6199999999999999
63
Mean accuracy: 0.665
64
Mean accuracy: 0.645
65
Mean accuracy: 0.64
66
Mean accuracy: 0.645
67
Mean accuracy: 0.61
68
Mean accuracy: 0.635
69
Mean accuracy: 0.6500000000000001
70
Mean accuracy: 0.685
71
Mean accuracy: 0.675
72
Mean accuracy: 0.69
73
Mean accuracy: 0.6649999999999999
74
Mean accuracy: 0.66
75
Mean accuracy: 0.74
76
Mean accuracy: 0.6950000000000001
77
Mean accuracy: 0.625
78
Mean accuracy: 0.6299999999999999
79
Mean accuracy: 0.6449999999999999
80
Mean accuracy: 0.6849999999999999
81
Mean accuracy: 0.66
82
Mean accuracy: 0.6599999999999999
83
Mean accuracy: 0.63
84
Mean accuracy: 0.69
85
Mean accuracy: 0.585
86
Mean accuracy: 0.67
87
Mean accuracy: 0.6049999999999999
88
Mean accuracy: 0.61
89
Mean accuracy: 0.63
90
Mean accuracy: 0.6399999999999999
91
Mean accuracy: 0.6749999999999999
92
Mean accuracy: 0.61
93
Mean accuracy: 0.6799999999999999
94
Mean accuracy: 0.635
95
Mean accuracy: 0.57
96
Mean accuracy: 0.705
97
Mean accuracy: 0.64
98
Mean accuracy: 0.66
99
Mean accuracy: 0.6599999999999999
100
Mean accuracy: 0.665

In [21]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("Boruta500_DEGs_Male_100RF.csv", index = False)

0.6500500000000001